### ISSUE TITLE
Link to thesis

### ISSUE THREAD

**Issue by behdad** [Chlumsky/msdfgen#10]
I see it's available here:
https://dspace.cvut.cz/handle/10467/62770
https://dspace.cvut.cz/bitstream/handle/10467/62770/F8-DP-2015-Chlumsky-Viktor-thesis.pdf

**Comment by Chlumsky** [comment]
Unfortunatelly, I came up with the far superior "direct method" (the one used in this project) a bit late in the process, so it is only described briefly and most of the thesis deals with the original "indirect method".

**Comment by behdad** [comment]
Humm, I thought it was covered fairly well.  But you're right, I was surprised that you even covered the indirect method at al, given how far superior the direct method is.

**Comment by behdad** [comment]
Made for a very nice airplane read BTW.  Thanks for writing it!

**Comment by ConnyOnny** [comment]
Nice read! Can you please put the link into the Readme.md? It's strange I have to check the "issues" of the project to find out how it works internally ;-)

**Comment by gitsomecrabs** [comment]
Do you have a sample of the your 2 and 3 channel signed distance field like you have for 1 channel signed distance field in Figure 1.2?

Thank you so much for doing that graphic.  You are the ONLY one to ever publish that and it help comprehension 500x for some of us.

**Comment by Chlumsky** [comment]
> Do you have a sample of the your 2 and 3 channel signed distance field like you have for 1 channel signed distance field in Figure 1.2?

@gitsomecrabs Not really, but here is an illustation of a discontinuous distance field, generated from only a subset of the shape's edge segments. The multi-channel distance field is composed of three such discontinuous distance fields.

![image](https://user-images.githubusercontent.com/18639794/55748136-2c58cc80-5a3e-11e9-9b72-f4a6290666a4.png)

**Comment by Chlumsky** [comment]
A link has been added to README.md.
