### ISSUE TITLE
No make install target?

### ISSUE THREAD

**Issue by robspearman** [Chlumsky/msdfgen#101]
I am creating a distro package (RPM) and wondering why I do not have an "install" make target.  Or is there some other automated install method that I can not find?

I am using Cmake 3.11.4.

**Comment by Chlumsky** [comment]
There is no need for it. It is just a single executable that doesn't need any extra files and can run from anywhere. Let's say it is "portable software." ;)

**Comment by robspearman** [comment]
I'm not using the executable, but packing up the library and headers.  I did this manually, just thought I was missing something.

**Comment by Chlumsky** [comment]
Ok, you can add it to the Cmake if you want. I didn't write it and personally don't use it.

**Comment by Type1J** [comment]
@robspearman You could make a PR to add the install (and maybe CPack) for the dynamic library and headers. I'm sure that would make other package manager's jobs easier.

Please also remember that many of us statically link by `add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/msdfgen")` in our own projects, where we disable the building of the binary. This is a great project, and what you're doing will improve its visibility.

**Comment by Chlumsky** [comment]
Resolved by #104.
