### ISSUE TITLE
Question: Proper scaling and positioning with freetype

### ISSUE THREAD

**Issue by vaheqelyan** [Chlumsky/msdfgen#108]
i know this is not the right place to ask this question, but I need help. 
this was the command I ended up using.

```
./msdfgen msdf -font Lato-Regular.ttf '72' -size 96 96 -pxrange 12 -autoframe -o ../basic-gl/H.png
```
i used FreeType 2 to provide the kerning, size, etc.

Here is my result (Lato Font, 40px)

![image](https://user-images.githubusercontent.com/14107127/87255761-96d79400-c45b-11ea-9fe8-dff9b85c739a.png)

I highlighted the characters

![image](https://user-images.githubusercontent.com/14107127/87255733-609a1480-c45b-11ea-88d5-fa68a732e43b.png)

Can you tell me how I can scale bitmaps or get the right metrics for rendering ? I mean, the character "H" should be a little wider
How can I maintain bitmap data along with generated textures

Here is a comparison of text in a web browser
![image](https://user-images.githubusercontent.com/14107127/87256064-c1c2e780-c45d-11ea-995d-a49cb26dafd0.png)

Here's what my fragment shader looks like
```glsl
#version 430 core
out vec4 color;

in vec2 uv;
in float layer_get;

layout (binding=0) uniform sampler2DArray textureArray;

float median(float r, float g, float b) {
    return max(min(r, g), min(max(r, g), b));
}

void main()
{
      vec3 flipped_texCoords = vec3(uv, layer_get);
      vec2 pos = flipped_texCoords.xy;
      vec3 dis = texture(textureArray, flipped_texCoords).rgb;
      ivec2 sz = textureSize(textureArray, 0).xy;
      float dx = dFdx(pos.x) * sz.x; 
      float dy = dFdy(pos.y) * sz.y;
      float sigDist = median(dis.r, dis.g, dis.b);
      float w = fwidth(sigDist);
      float opacity = smoothstep(0.5 - w, 0.5 + w, sigDist);
      color = mix(vec4(1.0,0.0,1.0,1.0), vec4(0.0,0.0,0.0,1.0), opacity);
}
```
This is the only progress I have made so far.
`./msdfgen msdf -font Lato-Regular.ttf '72' -size 96 96 -pxrange 12 -autoframe -scale 5 -o ../basic-gl/H.png`
![image](https://user-images.githubusercontent.com/14107127/87256220-aa382e80-c45e-11ea-9d28-25d68e98544d.png)

btw thank you for your software !

**Comment by Chlumsky** [comment]
First of all, don't use `-autoframe`. I even added a disclaimer on the front page but everyone still uses it and then wonders how to typeset with each letter scaled differently and centered (losing any sort of positioning). Then you gotta set the translation and scale that you compute with some sophisticated logic.

I don't know what exactly you're trying to do but I think you might want to take a look at https://github.com/Chlumsky/msdf-atlas-gen and see if it maybe solves the exact same problem you're working on.

**Comment by vaheqelyan** [comment]
thank you for your quick response
> First of all, don't use -autoframe

yeah i know, i used this command earlier

`./msdfgen msdf -font Lato-Regular.ttf '72' -size 96 96 -pxrange 12 -scale 2 -translate 3 20 -o ../basic-gl/H.png`

but i practically had the same problem as now

> I don't know what exactly you're trying to do but I think you might want to take a look at https://github.com/Chlumsky/msdf-atlas-gen and see if it maybe solves the exact same problem you're working on.

i store each image in a texture array, i don't use texture atlas.
can this cause a problem ?

**Comment by Chlumsky** [comment]
You can use a texture array, that's not a problem but you seem to have a hard time getting the positioning right, so I was thinking that you may want to use something that already has this solved.

**Comment by vaheqelyan** [comment]
ok i will try msdf-atlas-gen. I'll let you know. thank's.
