### ISSUE TITLE
Compatibility with Harfbuzz shaping engine

### ISSUE THREAD

**Issue by saidwho12** [Chlumsky/msdfgen#114]
Is there any way to get the `FT_Face` or `FT_Library` from _msdfgen_? The `FontHandle` and `FreetypeHandle` structures are opaque sadly, should I just move the implementation of these structures from their origin to this header, or is there a better way? I'm trying to render Arabic script using _OpenGL_.

I was able to generate the fields as you can see, and pack the characters into an atlas with reference.
![image](https://user-images.githubusercontent.com/70410392/95644489-03772480-0a85-11eb-8e2c-04ff40afac71.png)

I am simply wondering how this interop could work, I imagine I could just move the definition of these classes or extend the interface.

Thanks for the help.

**Comment by Chlumsky** [comment]
Yes, you can copy the header to your code, but I'm updating this project this weekend and was planning to add loading by glyph ID anyway so you can also just wait until I commit it.

**Comment by kamokiz** [comment]
What's rendering by glyph ID if you don't mind explaining? I don't think it will help my situation but I'm curious. Also thanks for the advice I'll just add a function to get the `FT_Face`, I need that cause at least from the example code of Harfbuzz this is what it's meant to look like, so I'm pretty sure I need access to that structure.

```
hb_buffer_t *buf;
buf = hb_buffer_create();
hb_buffer_add_utf8(buf, (const char *)text.c_str(), -1, 0, -1);
		
hb_buffer_set_direction(buf, HB_DIRECTION_RTL);
hb_buffer_set_script(buf, HB_SCRIPT_ARABIC);
hb_buffer_set_language(buf, hb_language_from_string("ar", -1));
		
FT_Face face;
FT_Library ft_library;
FT_Long face_index = 0;

FT_Init_FreeType(&ft_library);
FT_New_Face(ft_library, "../data/fonts/Amiri-Regular.ttf", face_index, &face);
FT_Set_Char_Size(face, 0, 8000, 0, 0);

hb_font_t *font = hb_ft_font_create(face, [](void *user_data) -> void {});
hb_shape(font, buf, NULL, 0);
```

**Comment by Chlumsky** [comment]
My library currently only supports loading glyphs by their Unicode value, but some glyphs don't have one, so they have to be loaded by some internal glyph index, which I suppose isn't even consistent across fonts but HarfBuzz somehow makes sense of it and gives these indices.

OK, so I will then make it so that you can create the `FT_Face` in your code and pass a copy to my library to create the `msdfgen::FontHandle`, would that be satisfactory?

**Comment by kamokiz** [comment]
Yeah that's pretty good, but I really just need a function to give me the already existing `FT_Face`... It's gonna be fine until this glyph ID system is in :)

**Comment by kamokiz** [comment]
As far as I know that's the only way to use Harfbuzz is with the FreeType handle, but I will keep reading the manual lest I find another way.

**Comment by Chlumsky** [comment]
See 38ef289f25e6e58c63a11dc6f1cb29dbf6c3d6a4.

**Comment by kamokiz** [comment]
Sorry, must I define `FT_FREETYPE_H` manually before including `msdfgen-ext.h` ??

**Comment by kamokiz** [comment]
Is there any difference in the shader with MTSDF and MSDF? I am trying to use the shader in the readme but only shows a flat color.

**Comment by kamokiz** [comment]
Is there any way to tell msdfgen to bake a specific pixel size for the characters?

**Comment by kamokiz** [comment]
Hey sorry to bother again, I did what you said and I'm using the glyph ID system though I am getting other kinds of issues. It's probably related to HarfBuzz itself and how it works but I couldn't find any info about it. I'm getting proper rendering in English but it breaks down in Arabic even though I included all unicode characters required, only things rendering is a select few number of accents, although the positioning of the quads and everything is fine.

I'm trying to render the following:
ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ

And this is the result:
![image](https://user-images.githubusercontent.com/70410392/95671345-dcdbeb00-0b63-11eb-8e49-8697d8f38e13.png)

With this mesh output:
![image](https://user-images.githubusercontent.com/70410392/95671332-a605d500-0b63-11eb-8734-8719de2d57d3.png)

Here I have the atlas map, it has the characters which are meant to be transitional or joint, yet it seems HarfBuzz is requesting a different character which doesn't exist, I have no idea what's going on.
![image](https://user-images.githubusercontent.com/70410392/95671359-20365980-0b64-11eb-8216-2747d1d09f18.png)

The following is the loop that gets the quad to update the text:
```cpp
for (u32 i = 0; i < glyph_count; ++i) {
	u32 codepoint = glyph_info[i].codepoint;

	FT_Load_Glyph(face, codepoint, FT_LOAD_NO_BITMAP);
				
	FT_Glyph_Metrics metrics = face->glyph->metrics;

	Rect<f32> srcRect {};
	if (!font.GetCharRect(&srcRect, codepoint))
	{
		printf("codepoint 0x%04x unfound in font\n", codepoint);
	}else{
		printf("codepoint 0x%04x found in font\n", codepoint);
	}

	FT_GlyphSlot slot = face->glyph;
				
	FT_Glyph glyph;
	FT_BBox  bbox;
	FT_Get_Glyph(slot, &glyph);
	FT_Glyph_Get_CBox( glyph, ft_glyph_bbox_subpixels, &bbox );
				
	f32 bearingX = slot->bitmap_left;
	f32 bearingY = slot->bitmap_top;
	u32 glyphW = metrics.width;
	u32 glyphH = metrics.height;

	f32 xa = glyphPositions[i].x_advance / 64.0f;
	f32 ya = glyphPositions[i].y_advance / 64.0f;
	f32 xo = glyphPositions[i].x_offset / 64.0f;
	f32 yo = glyphPositions[i].y_offset / 64.0f;
	f32 x0 = x + xo + bearingX;
	f32 y0 = floor(y - yo - bearingY);
	f32 x1 = x0 + glyphW/64.0f;
	f32 y1 = floor(y0 + glyphH/64.0f);

	Rect<f32> uvRect = srcRect / font.Dim();
	Swap<f32>(uvRect.y1, uvRect.y0);
	Rect<f32> realRect { x0, y0, x1, y1 };
	Rect<f32>::Fix( &realRect );

	CharQuad quad { realRect, uvRect, glm::vec4(0.0f, 0.0f, 0.0f, 1.0f) };
	Renderer::PushCharQuad(&textMesh, &quad);

	x += xa;
	y += ya;
}
```
If you have any ideas then please tell me, cause I'm out of them...

**Comment by kamokiz** [comment]
Do you know if HarfBuzz actually dynamically changes the glyph paths or if they keep the same shape for Arabic. Haven't been able to find any clear statement about it though from what I read they don't do that, still leaves me wondering why then I'm not able to retrieve these glyphs.

**Comment by kamokiz** [comment]
I just did a test, and _some_ the glyph indices given by msdfgen actually mismatch with the ones given by HarfBuzz, that's the source of the issue, this is the output for that same text string:

```
glyph index 427 corresponds to 427
glyph index 2590 corresponds to 418
glyph index 2562 corresponds to 423
glyph index 429 corresponds to 429
glyph index 2132 corresponds to 415
glyph index 427 corresponds to 427
glyph index 2078 corresponds to 391
glyph index 431 corresponds to 431
glyph index 2351 corresponds to 400
glyph index 428 corresponds to 428
glyph index 4551 corresponds to 418
glyph index 431 corresponds to 431
glyph index 2939 corresponds to 417
glyph index 462 corresponds to 462
glyph index 3 corresponds to 3
glyph index 427 corresponds to 427
glyph index 404 corresponds to 404
glyph index 5887 corresponds to 461
glyph index 427 corresponds to 427
glyph index 4127 corresponds to 398
glyph index 429 corresponds to 429
glyph index 430 corresponds to 430
glyph index 4381 corresponds to 402
glyph index 2264 corresponds to 417
glyph index 462 corresponds to 462
glyph index 3 corresponds to 3
glyph index 1962 corresponds to 388
glyph index 427 corresponds to 427
glyph index 4499 corresponds to 419
glyph index 429 corresponds to 429
glyph index 2099 corresponds to 396
glyph index 431 corresponds to 431
glyph index 2198 corresponds to 420
glyph index 462 corresponds to 462
```

**Comment by Chlumsky** [comment]
I'm not sure what you mean by "indices given by msdfgen", it doesn't *give* any indices. You're supposed to take them from HarfBuzz and pass them *to* msdfgen.

**Comment by kamokiz** [comment]
Ok

**Comment by kamokiz** [comment]
That doesn't work in my case though, let's say I want to create an atlas with a set of glyphs (unicode characters) and I store those bounds in a map using `msdfgen::getGlyphIndex()` as key, later when I get those same glyph indices from HarfBuzz they're totally incompatible except the accents.

**Comment by Chlumsky** [comment]
Because you need to process the text with HarfBuzz first to even know which glyphs you are going to need, use those to generate the atlas, and don't use `msdfgen::getGlyphIndex()` at all.

**Comment by kamokiz** [comment]
Ok interesting, do you know if there's any way from a list of unicode characters to generate the glyph indices using HarfBuzz? I've been trying to find a solution to this all day.

**Comment by kamokiz** [comment]
Cause I need all the glyphs in the language, and I don't know what text I'm gonna be rendering.

**Comment by Chlumsky** [comment]
I don't know how to do that, sorry. Maybe just use all glyphs that are available in the font? Or, a common approach is to dynamically generate the atlas on the fly.

**Comment by kamokiz** [comment]
If there's no solution I'll just use another text shaping library, cause this is just a pain, how can the glyph indices by arbitrary like that when those characters that it needs to render the line are already in the font under another value. I was even contemplating just making a lookup table from HarfBuzz to FreeType glyph indices manually, would be tedious and hackish but would fix the issue. I would be so happy if there's a way to just get those indices from HarfBuzz without having to shape anything cause what I have is a list of unicode values for the Arabic glyphs.

**Comment by kamokiz** [comment]
Yeah but on the fly it will be really difficult, I already am generating all the Arabic glyphs there's like a total of 1,282. It takes like 10 minutes to generate and the map has to be 4096x4096. I can do it but the issue is the glyph index FreeType gives you for a unicode character is not what HarfBuzz generates after shaping. I cannot do it on the fly sadly I'm targeting fairly weak hardware 😔.

**Comment by Chlumsky** [comment]
I'm just making sure, but you do realize that each Unicode character can have multiple different glyphs representing it depending on context and other factors and that's the entire point of HarfBuzz and text shaping in general, right?

**Comment by kamokiz** [comment]
Yeah I know, but how do I get a unique identifier for that specific glyph so I refer to it? There's only a finite set of unique glyphs in Arabic and I made sure to read the HarfBuzz docs it says that it doesn't actually dynamically modify the paths, only changes the glyphs and their position based on context.

**Comment by Chlumsky** [comment]
The glyph indices are specific to a given font file so that might be a problem. I'm afraid I can't help you any further because I only know about graphics and rendering but not so much about text shaping and Arabic.

**Comment by bjorn3** [comment]
Disclaimer: Everything I know about fonts comes from random articles I read on the internet. I don't have any experience with rendering fonts.

> There's only a finite set of unique glyphs in Arabic

The font may use an arbitrary context sensitive mapping between unicode characters and glyphs. To find all glyphs used for arabic, I think you would need to read all entries of the relevant tables mentioning an arabic unicode character and recursively expand it as necessary. There is no list of arabic glyphs in a font, as the same glyphs may be reused between arabic and non-arabic unicode characters.

**Comment by kamokiz** [comment]
Ok... thanks anyway my friend I'll ask the people behind HarfBuzz if they can help or I'll just read more docs / code hoping to find something.

This is what I been doing:
```
std::vector<u32> chars;
for (u32 i = 0x0600; i < 0x06FF; ++i) chars.push_back(i);
for (u32 i = 0xFB50; i < 0xFDFF; ++i) chars.push_back(i);
for (u32 i = 0xFE70; i < 0xFEFF; ++i) chars.push_back(i);


font.BakeMTSDF(chars);
```

I got these ranges from Wikipedia, and it does generate proper characters and packs them in a map. I was using `msdfgen::getGlyphIndex()` as the key to get those rectangles.

Later on in drawing I would look it up with the code that HarfBuzz gave me for rendering a quad and it would end up not being found, the reason must be that HarfBuzz doesn't calculate the glyph indices the same way as FreeType or msdfgen. I tried as well to index that map using the value from `hb_font_get_nominal_glyph()` but same idea the characters that change form were blank (unfound).

```

			for (u32 i = 0; i < glyph_count; ++i) {
				u32 codepoint = glyph_info[i].codepoint;
				//printf("glyph index %d corresponds to %d\n", codepoint, glyphIndices[i]);

				FT_Load_Glyph(font.GetFTFace(), codepoint, FT_LOAD_NO_BITMAP);
				
				FT_Glyph_Metrics metrics = font.GetFTFace()->glyph->metrics;
				FT_GlyphSlot slot = font.GetFTFace()->glyph;
				
				FT_Glyph glyph;
				FT_BBox  bbox;
				FT_Get_Glyph(slot, &glyph);
				FT_Glyph_Get_CBox( glyph, ft_glyph_bbox_subpixels, &bbox );
				
				PackedGlyph pg;
				if (!font.GetPackedGlyph(&pg, slot->glyph_index))
				{
					printf("glyph index 0x%04x unfound in font\n", slot->glyph_index);
				}
				
```

**Comment by kamokiz** [comment]
Actually I just saw something I think maybe it's a human error

**Comment by Chlumsky** [comment]
You said that you do know that a single Unicode character can be represented by multiple glyphs, but it doesn't seem that way. If you do it like this, you will only get *one* glyph per character - the default one. Then HarfBuzz will give you a different variant for that character and of course it won't be present in the atlas.

**Comment by kamokiz** [comment]
I do know that, but it shouldn't matter cause HarfBuzz gives me all the glyphs anyway, I just need to be able to link it to the atlas for rendering.

**Comment by kamokiz** [comment]
Thanks for the help, I'll try to figure out the rest myself :/

**Comment by christianparpart** [comment]
@saidwho12 maybe I missed it in this immense conversation here, but did you try (and succeed) in what you want with just using harfbuzz + freetype? I'm doing something similar (didn't take care about RTL though). :)

**Comment by saidwho12** [comment]
@christianparpart I don't know but thinking about this after I'm guessing the issue is that
