### ISSUE TITLE
Distance field sometimes gets reversed, either on part of the glyph or the entire glyph...

### ISSUE THREAD

**Issue by saidwho12** [Chlumsky/msdfgen#119]
I assume this is an issue with the direction of the path, no idea if this is a known issue or not. It doesn't happen on all fonts thankfully.

![image](https://user-images.githubusercontent.com/70410392/107721938-e3ae7200-6cab-11eb-8781-1b08f0b461df.png)

![image](https://user-images.githubusercontent.com/70410392/107722001-05a7f480-6cac-11eb-91d9-3ade0b97ea96.png)

The font I'm using for this is `LibreCaslonText-Regular.ttf`, I'm using freetype and passing the `FT_Face` to msdfgen. I wanna know is this easily solvable at all?

(edit 1)
This happens either on whole glyphs or parts of glyphs.

**Comment by saidwho12** [comment]
sometimes this happens as well, this is a Japanese font 
![image](https://user-images.githubusercontent.com/70410392/107730803-57f41000-6cc2-11eb-9d52-ae0dd5288602.png)

**Comment by saidwho12** [comment]
This seems to be fixed with the `winding()` and `reverse()` functions, I will try those and see...

**Comment by Chlumsky** [comment]
Yes, it is because of different directions of the path. Use `msdfgen::resolveShapeGeometry`.

**Comment by saidwho12** [comment]
Is there any way to fix this without skia? I am setting it up but it's quite large especially for my project.

**Comment by saidwho12** [comment]
The skia project is literally ~600MB, how hard really is it to implement this into msdfgen? Thanks for the solution btw I'll implement it for now but I have a feeling this might be a bit too large for my project which is a reading application. Maybe it's not too slow at runtime but the binary is very large. Another issue is I don't want too many dependencies, and skia has many by itself which sucks. If it's not too bad I'd be willing to try and solve this problem myself.

**Comment by saidwho12** [comment]
If the problem is just winding order for glyph paths and segments shouldn't it be something quite easy to solve?

**Comment by saidwho12** [comment]
@Chlumsky Do you have the file FindSkia.cmake? I have just built Skia but no idea how this should be structured.

**Comment by Chlumsky** [comment]
If it's easy to solve, then you can go ahead and solve it, that'd be quite helpful.

For some of the cases like the brackets and the "é", you can probably just use `Shape::orientContours`, but for other cases like the Chinese character, Skia is needed to resolve self-intersections. As for how to compile it with CMake, I don't use it so no idea.

**Comment by saidwho12** [comment]
Aight, I'll try get Skia working.
