### ISSUE TITLE
distanceFactor

### ISSUE THREAD

**Issue by caperaven** [Chlumsky/msdfgen#123]
I am trying to understand the distance factor explanation as per
https://github.com/Chlumsky/msdfgen/issues/36

You have a target rectangle of 48x64
The source texels is 15x20

Can anyone please help me understand how that gives me a ratio of 3.2.
I am unsure of what formula is applied to give me that value.

Yes I am aware that I am a noob so any assistance would be greatly appreciated.

**Comment by Chlumsky** [comment]
This is properly explained in the [Readme](https://github.com/Chlumsky/msdfgen#using-a-multi-channel-distance-field). 48/15 = 64/20 = 3.2. Post questions like this in discussions, not issues.

**Comment by caperaven** [comment]
> This is properly explained in the [Readme](https://github.com/Chlumsky/msdfgen#using-a-multi-channel-distance-field). 48/15 = 64/20 = 3.2. Post questions like this in discussions, not issues.

I can understand that you may be frustrated by such stupid questions but thank you for taking the time in answering it anyway.
I really appreciate it
