### ISSUE TITLE
Texture size is always changed

### ISSUE THREAD

**Issue by Hendrik-Lober** [Chlumsky/msdfgen#128]
Currently it is very hard to foster image size and feature consistency between the input and the output. There seems to be no good way to keep the original texture size and relative shape positions intact.
EXAMPLE:
If I input a 1024px Texture with a smilie face on it that has a distance of 100px to the borders of the texture and I am using a distance of 10px, then the output will have 1024px but -autoframe will have cut the texture to exactly the SDF omitting 90px on each side. Scaling and translating is an option but did not yield good results without a lot of fiddeling with the values.
PROPOSAL:
Introduce an option for the -autoframe parameter or another option called "-clip" that will clip the output to the specified canvas size of the input SVG, thus keeping relative shape positions to the borders intact

**Comment by Chlumsky** [comment]
Seems to me like there shouldn't be an issue setting the scale to the right value but you didn't include a file so no way to test. Maybe try looking at the beginning of [this comment](https://github.com/Chlumsky/msdfgen/issues/109#issuecomment-666992385).

**Comment by Hendrik-Lober** [comment]
I checked our SVG file again and it is set to 4097pt which amounts to 5462,666px. Our output size is 4096px so a factor of 0.74982 should produce a perfectly aligned image, which it does.
This solves our issue and provides us with a consistent base for our outputs. I still would propose an -autoscale parameter since this situation is very common and it would further improve the scripts usability.
Thank you very much for your quick answer and the time and dedication you put into your thesis! And of course for making your code publicly available and in such a manner that your precompiled application is extremely easy to use!
