### ISSUE TITLE
SVG input format specs

### ISSUE THREAD

**Issue by geeklystrips** [Chlumsky/msdfgen#13]
It seems I am unable to feed an SVG file with the proper specs. Would you happen to have an example we can use for comparison?

Edit: A description of how a proper SVG output is obtained in the first place would also be very useful. Inkscape? Illustrator? My attempts at creating the simplest shapes have failed so far. I'm actually having more success creating a dummy TTF file with the vector shapes and then feeding that TTF to msdfgen with the -font option :)

**Comment by Chlumsky** [comment]
Yes, I didn't want to waste time by implementing a comprehensive SVG decoder, so it is pretty limited, but I was always able to generate something the program could read with Inkscape, although sometimes it was easier to help it with a text editor. Basically it reads the first &lt;path&gt; element (which must be in &lt;svg&gt; and can be in a single &lt;g&gt;). If it is wrapped in more stuff, it won't find it, yeah. Also, sometimes the path has the wrong order (winding? chirality?) and the distance field is inverted. Anyway, here is an example working file:

[blob.zip](https://github.com/Chlumsky/msdfgen/files/307555/blob.zip)

**Comment by geeklystrips** [comment]
This shape works fine!

I haven't had time to test thoroughly with formats and options, but just in case this info can be useful to anyone:

- None of the SVG files exported by Illustrator CS6 are accepted. I think I tried all the different output options, so I gather something is indeed weird with the XML structure.
- A simple shape created in Inkscape goes through.
- A simple shape created with Illustrator, saved as SVG, opened and saved again by Inkscape does not go through. This seems to indicate that whatever Adobe specifications is causing problems with the Illustrator SVG tags along to Inkscape.

Thanks for your answer :)

**Comment by boulabiar** [comment]
Add Z to the end of the path in the svg and it will work
(in my case ending the d="M .....Z" with that Z solved the problem)

**Comment by Chlumsky** [comment]
Support for multiple paths / shapes in an SVG file added in 0286aeb6eb452ec1cd9636b43cf303d33f61eb31.
