### ISSUE TITLE
Is it possible to use your technique in my engine?

### ISSUE THREAD

**Issue by QuantumDeveloper** [Chlumsky/msdfgen#130]
Hi. I am trying to implement good font rendering algorithm for my own game engine and found your repo here. 
I started looking in your paper, but found a licensing conflict between this repo and a paper. 
Repo has MIT license, but paper prohibits to use your technique for commercial use. 
As far as I have plans for possible commercial use of my engine in future, I want to ask you about the licensing. 
Can I reimplement your technique for my engine using C#?

**Comment by Chlumsky** [comment]
I am not aware of anything being prohibited for commercial use, can you specify where exactly it says that?

Of course you can reimplement it in C# if you wish, although I think it might be simpler to just use the existing implementation, e.g. as a DLL.

**Comment by QuantumDeveloper** [comment]
Here is the screen in the paper where I found this
![image](https://user-images.githubusercontent.com/6085009/133491509-ea8e76cb-f127-4d68-89d6-e3c5cf3cfce8.png)

**Comment by Chlumsky** [comment]
Well, this was something that was required to be included by the school and I didn't question it and don't really understand the exact implications, but I believe that the software in this repository is provided independently from the thesis and therefore only the MIT license applies to it. But maybe it means that if you wanted to reimplement it in C#, you have to forget what you read in the thesis or you're breaking the law. ;)

**Comment by QuantumDeveloper** [comment]
Thanks for your answer :)
