### ISSUE TITLE
Want descriptions for right scale & translate value.

### ISSUE THREAD

**Issue by hak** [Chlumsky/msdfgen#14]
Could you give me a description to retrieve right values for scale and translate value in msdfgen::generateMSDF() ?

For example, given Bitmap<FloatRGB> is set up with a size of 16x24,
what is a recommended method to retrieve the scale and translate values to make the glyph located at the center of the area with the size?
# BTW, the msdf method is awesome!! I'm really happy with the result so far.

**Comment by Chlumsky** [comment]
If you use the -autoframe switch, it should be correctly scaled and centered. If you also use -printmetrics, it will tell you what scale and translate values have been used to achieve it. It will also tell you its bounding box (LBRT).

Basically, if your glyph is 160 units wide and you want it to be 16 pixels wide, you set the scale to 0.1. If the lower left corner is not at (0, 0) but e.g. at (60, 80) (in the original glyph units), you translate by (-60, -80).

**Comment by hak** [comment]
Thanks for the pointer. That helps a lot!

**Comment by boulabiar** [comment]
So the bounding box helps getting the letter box that can be directly used for packing in a texture atlas/map? Or it should be a little bit bigger ?
