### ISSUE TITLE
Why does the command line interface's font input mode convert font units to pixels by dividing by 64?

### ISSUE THREAD

**Issue by TJYSunset** [Chlumsky/msdfgen#147]
Sorry if this have already been mentioned before.

I'm no expert in typography, but if I'm not mistaken -
- [The call to `FT_Load_Glyph`](https://github.com/Chlumsky/msdfgen/blob/4e8ff2321ea9696801675c908a4822c4d8e71eb8/ext/import-font.cpp#L179)  set the `FT_LOAD_NO_SCALE` flag, [so](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyph_metrics) its return value is expressed in the exact **font units**, *not* **26.6 fractional pixels**;
- The typical **font unit** to **em** ratio is [either 1000:1, 1024:1 or 2048:1](http://designwithfontforge.com/en-US/The_EM_Square.html), and is retrievable as [`FT_FaceRec.units_per_em`](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_facerec);
- 1 **em** [equals the currently specified **pt** size](https://en.wikipedia.org/wiki/Em_(typography));
- **Pixels** per **pt** [depends on the DPI](https://freetype.org/freetype2/docs/tutorial/step1.html#section-5), which is typically [72, 96 or 300+](https://en.wikipedia.org/wiki/Dots_per_inch);
- None of the above conversions involve a multiplier/divisor of 64.

To be clear, I don't think this behavior needs "fixing" (changing the behavior will only break existing code). It just needs clear documentation in the README.

**Comment by Chlumsky** [comment]
Can you point out the specific division that you think is incorrect? I believe it is done to convert FreeType's fixed point number format (integer whose most significant 26 bits are the whole part and least significant 6 bits are the fractional part) to floating point.

**Comment by TheFungineer** [comment]
Sorry to resurrect this, but I found out that, even though the freetype documentation indicate that FT_Load_Glyph with the FT_LOAD_NO_SCALE flag will yield outline points in 2:2 font units, if you look at the actual code (for TrueType fonts at least) they convert the outline points from font units to a 26.6 fixed float on load (64th of font units). So the current code should be working (for truetype fonts at least). You can look at the code here: https://github.com/freetype/freetype/blob/master/src/truetype/ttgxvar.c#L4234

**Comment by Chlumsky** [comment]
Fixed in bc9f02e156115860e28094565c57d383ab03b761, hopefully with full backwards compatibility.

Use:
- `-noemnormalize` / `FONT_SCALING_NONE` to switch to the correct native font coordinates,
- `-emnormalize` / `FONT_SCALING_EM_NORMALIZED` to switch to coordinates normalized to 1 em, or
- `-legacyfontscaling` / `FONT_SCALING_LEGACY` to keep old behavior and make sure it will not change.

If you do not specify any of the above, you will get a warning in the console version, but for now, the old behavior will be kept.
