### ISSUE TITLE
Distance field flips depending on TTF/OTF file.

### ISSUE THREAD

**Issue by hak** [Chlumsky/msdfgen#15]
Generated SDF flips depending on TTF/OTF file.
For example, in 'Times New Roman.ttf' (coming with OSX), SDF is generated for outer direction
while in 'NotoSansCJKjp-Bold.otf' (https://www.google.com/get/noto/), it's generated to inner direction.

Need to check a winding direction for a robust SDF generation?

**Comment by daredevildave** [comment]
I've found some other fonts that appear to be inversed, either completely or partially.

This one seems to be completely inverse: http://www.dafont.com/sports-world.font

**Comment by Chlumsky** [comment]
So does the font file specify which direction it uses or am I supposed to guess it from the geometry somehow? Unless it does, I'm thinking of just adding a switch that will invert it. Anyway, for now, you should be able to fix the distance field if you just invert the colors.

**Comment by behdad** [comment]
TrueType-flavored OpenType fonts (aka TTF) conventionally have clockwise outer contours, while CFF-flavored ones (aka OTF) have the reverse.  That said, these are conventions, and both work perfectly fine in most apps if they do not follow the convention.  I have some code in GLyphy for fixing up contour directions if you care to check.

**Comment by boulabiar** [comment]
I had the same problem with svg downloaded from thenounproject.com

**Comment by Chlumsky** [comment]
I have added an option (-reverseorder) that will fix the output for shapes defined in reverse order.

**Comment by chaoticbob** [comment]
@Chlumsky - I borrowed the logic from [invertColor ](https://github.com/Chlumsky/msdfgen/blob/master/main.cpp#L134-L141)for OTF fonts and the result looks in correct. I changed the 0.5 to 1.0 and it seems to produce correct results.  Wondering if I'm missing something on this? Font is [Chalet Comprime Cologne 1980](http://www.houseind.com/fonts/chaletcomprime). It also lives in various places on the internet. 

Also wondering if anyone has seen this on TTF font as well?

**Comment by daredevildave** [comment]
The -reverseorder flag doesn't seem to be working correctly as noted above.

Compare the two results below. First is generated using no -reverseorder flag and then the image is inverted in graphics magic. Second is generated using -reverseorder flag. 

I believe the error is as noted above. If you change the value in invertColor from 0.5 to 1.0. The results come out the same.

![sports world-correct](https://cloud.githubusercontent.com/assets/504980/20962163/2249315e-bc60-11e6-8afb-0fa2733544c2.png)
![sports world-wrong](https://cloud.githubusercontent.com/assets/504980/20962162/2246e688-bc60-11e6-86f2-1cf091eef50b.png)

**Comment by Chlumsky** [comment]
You are absolutely right, sorry, I have no idea how I overlooked this.

**Comment by vkalpias** [comment]
I noticed a peculiar thing after your latest fix. Some fonts are almost invisible using the simple shader after using reverseorder but if we use imagemagick they're fine. Here is an example using reverseorder:

![using_reverseorder](https://cloud.githubusercontent.com/assets/850969/21007545/04628a3c-bd46-11e6-8dda-09fd8fce47a9.png)

and the same font using imagemagic to invert it

![invert_imagemagick](https://cloud.githubusercontent.com/assets/850969/21007552/0bff557c-bd46-11e6-8586-803657694588.png)

Is there a solution for this?

**Comment by Chlumsky** [comment]
Could you please provide the data necessary to reproduce this, or at least the unmodified outputs with and without -reverseorder?

**Comment by vkalpias** [comment]
I'm not sure I can give you the font because it's from a client and I'm not sure if it's licensed or not. But here is the output for one character: 

This is without reverseorder:

![33](https://cloud.githubusercontent.com/assets/850969/21020353/cf45ebb4-bd7c-11e6-904d-7fe8921f87b4.png)

This is with reverseorder:

![33 2](https://cloud.githubusercontent.com/assets/850969/21020360/d6ddb01e-bd7c-11e6-825d-76c35e4da74c.png)

This is the first image negated with imagemagick:

![33_negative](https://cloud.githubusercontent.com/assets/850969/21020362/dc774134-bd7c-11e6-9ebd-339daaf938bc.png)

In the docs of imagemagick here it says that -negate takes the complementary color. Is that slightly different? Link: https://www.imagemagick.org/script/command-line-options.php?#negate

**Comment by Chlumsky** [comment]
I'm not getting the same behavior. Actually, what you're claiming is the output with reverse order looks a lot like what would happen before the fix.

**Comment by vkalpias** [comment]
Looks like you're right. I had a weird local merge on my fork of your repo which seemed to use the old version! Thanks and sorry I'll delete my posts.

**Comment by Chlumsky** [comment]
Since 0e68504f44ad156b8e73773d056a98c8dfdc61db, the standalone version will automatically guess the orientation of the input by sampling a distance outside the shape's bounds. This can be disabled by `-keeporder` or `-reverseorder`.
