### ISSUE TITLE
Mplus1 font artifacts

### ISSUE THREAD

**Issue by wdanilo** [Chlumsky/msdfgen#162]
Hi, I'm using the [M PLUS 1 font](https://fonts.google.com/specimen/M+PLUS+1?query=plus). It is a variable one so I'm using the API exposed in [this PR](https://github.com/Chlumsky/msdfgen/pull/158). Unfortunately, glyphs are rendered with some artifacts:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1623053/186165684-9adac6ee-613e-4b0e-8db2-5252f351d299.png">

@Chlumsky do you think you'd find a minute to take a look at it? I'd be insanely thankful for your help here.

**Comment by Chlumsky** [comment]
Use a version with Skia preprocessing.
