### ISSUE TITLE
Msdf generation fails on symbol with several nested holes

### ISSUE THREAD

**Issue by Dollab** [Chlumsky/msdfgen#170]
Hi, first of all thanks a lot for this amazing library.

I've encountered a specific shape that seems to produce an error in the output msdf. You can see below the svg file describing the shape, the resulting msdf and an example of a render using the msdf.

The upper left hand rectangle should be hollowed but it's marked as "filled".

The results can be reproduced with the following code : 
```c++

#include "msdfgen.h"
#include "msdfgen-ext.h"
#include <iostream>

using namespace msdfgen;

int main()
{
    std::cout << "Converting svg..." << "\n";
    Shape shape;

    if (loadSvgShape(shape, "./assets/floor.svg", 0)) {
        shape.normalize();
        //                      max. angle
        edgeColoringSimple(shape, 2.0);
        //           image width, height
        Bitmap<float, 3> msdf(3*24, 3*24);
        //                     range, scale, translation
        generateMSDF(msdf, shape, 2.0, 3.0, Vector2(0.0, 0.0));
        savePng(msdf, "./textures/output.png");
        simulate8bit(msdf);

        Bitmap<float, 1> test(256, 256);
        renderSDF(test, msdf, 1.0, 0.5);
        savePng(test, "./textures/test.png");
        std::cout << "Success!" << "\n";

    }

    return 0;
}
```

![floor](https://user-images.githubusercontent.com/7534544/205481437-c01557ff-2d44-4e45-9a5f-602809be076f.svg)
![output](https://user-images.githubusercontent.com/7534544/205481440-6bad06e2-712d-4364-8eb6-d58217713d44.png)
![test](https://user-images.githubusercontent.com/7534544/205481442-0d1df46a-8849-4cf9-8c88-5921d728a3f7.png)

**Comment by Chlumsky** [comment]
You either need to provide a correctly formed shape with consistent contour windings or use the Skia preprocessing.

**Comment by Dollab** [comment]
Thanks a lot for the superfast response. 
I'm not too versed in vcpkg, but I can't seem to find the skia feature ?

**Comment by Chlumsky** [comment]
Not sure what you mean, but the vcpkg feature is called `geometry-preprocessing` and it is enabled by default.

**Comment by Dollab** [comment]
Yes, my bad I works perfectly thanks !
