### ISSUE TITLE
Allow FT_LOAD_DEFAULT in import-font extension

### ISSUE THREAD

**Issue by malytomas** [Chlumsky/msdfgen#172]
Would it be possible to add additional parameter to this function:
https://github.com/Chlumsky/msdfgen/blob/7ff249bcd4da6678c5779d9664633c039fb50c0a/ext/import-font.cpp#L178
to allow replacing FT_LOAD_NO_SCALE with eg. FT_LOAD_DEFAULT?

This would allow me to set size for the font and use hinting (which is disabled with FT_LOAD_NO_SCALE).
Hinting would make the text better readable for the particular size while still maintaining scalability of the msdf.

**Comment by Chlumsky** [comment]
How would it help with hinting when FreeType's rasterizer is not being used?

**Comment by malytomas** [comment]
Freetype applies hinting when loading the glyph, changing the outlines. It is not necessary to use the rasterizer for that.

**Comment by malytomas** [comment]
here is a comparison, all else equal.

no hinting:
![typo-without](https://user-images.githubusercontent.com/18198295/219516927-4b24923c-4208-407e-b2ea-d9e818f68ccd.png)
![skins-without](https://user-images.githubusercontent.com/18198295/219516933-806c4661-1591-443c-ad8e-c310eb786d1a.png)

with hinting:
![typo-with](https://user-images.githubusercontent.com/18198295/219516935-387b360e-e3a1-48fc-89cd-5e15f604a5af.png)
![skins-with](https://user-images.githubusercontent.com/18198295/219516930-0595797f-e105-4960-835f-52591f41e033.png)

where to focus:
- in the second picture, the words _morituri te salutant_ in bottom right corner, _i_ and _l_ are barely visible without hinting
- the caption _compact skin_ in top right, second image
- the words _žluťoučký_ and _ďábelské_ in the first picture, the roboto font

please note, i am using just one msdf per font. the hinting allows making better msdf texture, which improves rendering irrespective of the final scale when rendering actual text.

**Comment by Chlumsky** [comment]
It seems that you have access to `FT_Face` since you can set the scale, so this should work for you: eeec8f2

**Comment by malytomas** [comment]
This works for me. Thank you.
