### ISSUE TITLE
Inverting Y Axis makes uneven baseline

### ISSUE THREAD

**Issue by noorwachid** [Chlumsky/msdfgen#178]
``` cpp
scale = 1.0f / metrics.emSize; // metrics from getFontMetrics
float atlasScale = 1.0f / atlasPx; // atlasPx is the size of texture atlas

TextCharacterInformation info;

info.position.x = 0;
info.position.y = scale * bounds.b; // bounds from shape.getBounds
// info.position.y = 1.0f - (scale * bounds.t); // Activate if using Y is down or shape.inverseYAxis = true
info.size = scale * size;

info.textureIndex = hotTextureIndex; // the texture that still has free space
info.texturePosition = atlasScale * Vector2(xOffsetPx, yOffsetPx); // offsetPx is the carriage from atlas packing
info.textureSize = atlasScale * subbytesSize; // subbytesSize is the size of bitmap from generateMSDF
```

<img width="1203" alt="Screenshot 2023-04-15 at 20 58 22" src="https://user-images.githubusercontent.com/42460975/232228937-e03ef3e6-54b2-4da4-ae72-ffe873b71261.png">

<img width="1201" alt="Screenshot 2023-04-15 at 20 53 26" src="https://user-images.githubusercontent.com/42460975/232228943-d68df3db-14ba-40d6-932c-1c5496e2c419.png">

Some glyph like v and z are hovering above baseline.
<img width="1096" alt="Screenshot 2023-04-15 at 21 01 48" src="https://user-images.githubusercontent.com/42460975/232229048-d52fe3b4-4271-431c-9397-2f375d51e685.png">

**Comment by Chlumsky** [comment]
And what exactly makes you think that the bug is in msdfgen and not in your code?

**Comment by Chlumsky** [comment]
Reopen when you provide a way to reproduce this and show how this is a bug in msdfgen.
