### ISSUE TITLE
The effect of render small character is not good

### ISSUE THREAD

**Issue by sry948749099** [Chlumsky/msdfgen#182]
Hello,
   I'm generating a 32x32 multi-channel distance field generated by this program with pxrange 2, and it is used to render text with 16x16 pixels font size on the screen, but i found the render effect is not good. like this:
![20230717-195419](https://github.com/Chlumsky/msdfgen/assets/56307410/eb521a7b-8b18-4899-a7cc-ccb759977f62)
  This is my shader:
![20230717-195427](https://github.com/Chlumsky/msdfgen/assets/56307410/8b97fa18-2aa7-4cbd-9665-9656f269d45a)
  so, could you help me to analyze the reasons, or what are the effective solutions.

**Comment by Chlumsky** [comment]
For downscaling, you need higher pxranges than 2 (proportional to the downscale). You should also make sure your shading is sRGB-correct. Otherwise, I'm not sure what you mean by "not good."

**Comment by sry948749099** [comment]
> For downscaling, you need higher pxranges than 2 (proportional to the downscale). You should also make sure your shading is sRGB-correct. Otherwise, I'm not sure what you mean by "not good."


How to make my shading to be sRGB-correct? “not good” means the first picture's render effect is not good, the jagged effect is obvious。
I tried to increase my pxrange value and render it through the above shader, but the rendered characters are very weak and thin.
