### ISSUE TITLE
Failure to import SVG file with empty initial <g> element

### ISSUE THREAD

**Issue by treacherousfiend** [Chlumsky/msdfgen#185]
When importing an SVG file with multiple `<g>` elements, if the uppermost one has no path, msdfgen will fail to import with the "Failed to load shape from SVG file." error.
These files do import correctly into Inkscape and Krita, and you can reproduce an erroring SVG file yourself with Inkscape by creating an empty layer which is a parent for other layers which have paths in them
![image](https://github.com/Chlumsky/msdfgen/assets/46549454/4565e453-da78-4a1b-806e-f85ae2e80296)

Alternatively, I have 2 error inducing SVG files below, one made via a blender plugin to convert curves into SVG, and one that is made in Inkscape using the method above
[blenderpluginsvg](https://github.com/Chlumsky/msdfgen/assets/46549454/7bb5dc2d-a20c-424d-9d03-ac42bf33c12f)
[inkscapesvg](https://github.com/Chlumsky/msdfgen/assets/46549454/01544b0c-097e-443b-bca2-d5c1e66193ac)

**Comment by Chlumsky** [comment]
I am not able to reproduce this problem. Are you using the latest version?

**Comment by treacherousfiend** [comment]
I'm using the latest release, should I try to build the current commit?

**Comment by Chlumsky** [comment]
Yes, SVG parser was updated after the 1.10 release.

**Comment by treacherousfiend** [comment]
that worked, thanks!
