### ISSUE TITLE
Incorrect rendering of SVG with internal path

### ISSUE THREAD

**Issue by pgrAm** [Chlumsky/msdfgen#188]
Hi I have been having some issues with some svg files that contain self instersecting/internal paths.

For example I used this svg with the latest version of the master branch (which contains the updated svg code)

![simple](https://github.com/Chlumsky/msdfgen/assets/3148945/3bc0f9ed-c474-43a7-8708-55269c50410a)

I ran the the tool with these arguments

`msdfgen -svg simple.svg -autoframe -size 128 128 -testrender render.png 512 512`

However the results were not as expected, as you can see there is no "A" embedded in the circle like in the SVG

render.png:
![render](https://github.com/Chlumsky/msdfgen/assets/3148945/d8bc0e6f-a5c7-453f-a111-7dc93c0a7c7c)

output.png:
![output](https://github.com/Chlumsky/msdfgen/assets/3148945/0a73ce2b-1d4f-4028-8584-24b09a39aaee)

**Comment by Chlumsky** [comment]
Thank you for reporting this. The issue was that the `fill-rule` attribute was not taken into consideration. This was fixed in f04dc6a. Keep in mind that like the previous improvements to the SVG parser, this will only work in the version with Skia.
