### ISSUE TITLE
SVG with Quadradic path commands generates an SDF instead of MSDF

### ISSUE THREAD

**Issue by rtrick** [Chlumsky/msdfgen#195]
First off, thank you for all the amazing work on this tool, it unlocks so much amazing art potential!

We believe we've found an unexpected behavior when processing some SVGs.  Some of the SVGs we try to send through msdfgen appear to generate monochrome SDFs rather than MSDFs.

We believe we've isolated this to when an SVG has curve path commands.  If the image only uses lines and arcs, we get an MSDF that renders as expected.

This is the unexpected result, generated from an SVG with curve commands
**SVG:**
![HasQuadratic_ImportsAsSDF](https://github.com/Chlumsky/msdfgen/assets/60235797/ffa7a7ae-2277-40b4-8243-9afa9190afd4)
**Output SDF:**
![HasQuadratic_ImportsAsSDF](https://github.com/Chlumsky/msdfgen/assets/60235797/db13ef23-697c-438a-9105-78a5efd5960f)
**Example render of the inner corner:**
![Example_IncorrectlyRoundedInnerCorner](https://github.com/Chlumsky/msdfgen/assets/60235797/302eabc1-e7c7-4e92-9b8f-ce542f93ea3d)

This is a the expected result generated from an SVG with only line and arc commands
**SVG:**
![OnlyLinesArcs_ImportsAsMSDF](https://github.com/Chlumsky/msdfgen/assets/60235797/c68b89f3-b606-4c76-85e6-f529f6ba7b88)
**Output MSDF:**
![OnlyLinesArcs_ImportsAsMSDF](https://github.com/Chlumsky/msdfgen/assets/60235797/bdecddec-62be-4cb5-990f-6d0f4b2fd8ee)
**Example render of the inner corner:**
![Example_CorrectlyRoundedInnerCorner](https://github.com/Chlumsky/msdfgen/assets/60235797/ea864e5a-b5e6-4af9-a4f5-ad3d835f8a2a)

**Comment by rtrick** [comment]
One of my teammates let me know that this is probably also important info for the report: We use a skia-enabled build of msdfgen, and we use skia for SVG parsing, not the default SVG parser.

**Comment by Chlumsky** [comment]
MSDF only takes care of sharp corners. Your SVG has rounded corners.

![image](https://github.com/Chlumsky/msdfgen/assets/18639794/c1579e0d-5a5a-47b4-b77a-8e37c73e8248)

**Comment by rtrick** [comment]
Ah!  I see.  So even if at the rasterized resolution the edge looks "sharp" it needs to be a literal sharp corner to trigger the MSDF behavior.

This makes sense, as in our data, it seemed that the SVGs made in vector tools seemed to work reliably, but traced raster images more often had the issue.

Thanks so much for the clarity!  We now know how to clean our data set.  I think it would be reasonable to close this issue, though it would certainly be cool if there were some feature that could handle this automatically.

Thank you!
