### ISSUE TITLE
Multiple character output

### ISSUE THREAD

**Issue by ydemir61** [Chlumsky/msdfgen#196]
Hello, how can I output multiple characters as shown in the picture and then get the json file? I couldn't figure out the command.

![1](https://github.com/Chlumsky/msdfgen/assets/85315847/125ecf43-c4ee-427e-a191-d2232abcb1d7)
![2](https://github.com/Chlumsky/msdfgen/assets/85315847/22a421c5-5eb3-45ca-9f69-fb751f3dca91)

**Comment by Chlumsky** [comment]
Not supported. Try msdf-atlas-gen.
