### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by sry948749099** [Chlumsky/msdfgen#198]
Mode: MSDF
pxRange: 6
font size: 32
render size: 32

font file:
[NotoSansArabic-Regular.zip](https://github.com/Chlumsky/msdfgen/files/14740703/NotoSansArabic-Regular.zip)

render results:
![issue](https://github.com/Chlumsky/msdfgen/assets/56307410/e558dd4f-693b-494e-8b91-f410fffd5832)

**Comment by sry948749099** [comment]
> Mode: MSDF pxRange: 6 font size: 32 render size: 32
> 
> font file: [NotoSansArabic-Regular.zip](https://github.com/Chlumsky/msdfgen/files/14740703/NotoSansArabic-Regular.zip)
> 
> render results: ![issue](https://private-user-images.githubusercontent.com/56307410/316429630-e558dd4f-693b-494e-8b91-f410fffd5832.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTQ0ODUsIm5iZiI6MTcxMTM1NDE4NSwicGF0aCI6Ii81NjMwNzQxMC8zMTY0Mjk2MzAtZTU1OGRkNGYtNjkzYi00OTRlLThiOTEtZjQxMGZmZmQ1ODMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA4MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZGMwNGQ5NDhmZjVhNjEwYzlmNjE0OThiNDQxYzcxNTY2N2JiYzk5ZDQ3NzVkYjZiMTVjNGI4MTdjN2JjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wvZ2CDhoArZIEEtwYdZ1twgAZXmH7gTiCs83leZSYgk)

Rendering results have holes in corners

**Comment by Chlumsky** [comment]
The font has self-intersecting geometry, therefore you must use Skia preprocessing (`-preprocess` or `msdfgen::resolveShapeGeometry`).
