### ISSUE TITLE
SDF from glyph curves?

### ISSUE THREAD

**Issue by jay3d** [Chlumsky/msdfgen#199]
I will start with this question: Does msdfgen use the glyph **outlines** directly? Or is it just using the **rasterized** output from FreeType?

![image](https://github.com/Chlumsky/msdfgen/assets/2527637/9ded60aa-4929-41ef-b1f5-bfd70097929c)

Because the scaled output above suggests otherwise.

Since the curve subdivisions are not really customizable in FreeType (it's calculated based on the raster size), so I _"guess"_ this is translated to the generator.

If this is the case, then I suggest using an SDF Bezier function (quadratic/cubic) to generate the SDF output from the glyph outlines directly.

https://www.shadertoy.com/view/7sKfR1

**Comment by Chlumsky** [comment]
Thanks for the tip. It uses curves directly, what you are seeing are the _line_s from the bi_line_ar filtering of the SDF raster.

**Comment by jay3d** [comment]
![image](https://github.com/Chlumsky/msdfgen/assets/2527637/90b27b73-c143-4b29-bffd-72d516ed2884)

I have solved it by using a custom bicubic texture lookup method :)
