### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Chlumsky/msdfgen#2]
Would you like to [add more error handling for return values](https://github.com/Chlumsky/msdfgen/blob/61d3929db06692a9b95fa0bee0bdf411c708fac6/main.cpp#L128) from calls of [the function "fprintf"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html)?

**Comment by Chlumsky** [comment]
Would you find something like this sufficient?

```c
if (fprintf(file, ...) < 0)
    return false;
````

**Comment by elfring** [comment]
How do you think about to check against an other value (instead of zero) for such a function call?

**Comment by Chlumsky** [comment]
Is this a quiz? It says that a negative value means an error. Honestly, I'm not really that concerned with flawless error handling in a simple command line utility.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") generally.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by zao** [comment]
I suggest focusing on not listening to language lawyers and "code improvement" crusaders on github, whose indirect mission is to waste time in as many open source projects as possible.
