### ISSUE TITLE
Fix incorrect color scaling factor

### ISSUE THREAD

**Issue by prepare** [Chlumsky/msdfgen#20]
from @Michaelangel007,

@Chlumsky 
Is this your intention?

https://github.com/Michaelangel007/msdfgen/commit/79c65458de12518b66da0ab5d8a6d53710d40724

**Comment by Chlumsky** [comment]
I have already explained [here](https://www.reddit.com/r/gamedev/comments/4ij5ih/new_realtime_text_rendering_technique_based_on/d2ytegt) that it is not incorrect. I'm not going to change it unless someone shows me a definitive proof that I'm wrong.

**Comment by prepare** [comment]
👍   Thank you :)

**Comment by behdad** [comment]
I agree existing code is correct.
