### ISSUE TITLE
Error when glyph starts with Quadratic Point

### ISSUE THREAD

**Issue by prepare** [Chlumsky/msdfgen#21]
please see  a problem and  a solution in this  https://github.com/Chlumsky/msdfgen/pull/19

**Comment by Chlumsky** [comment]
Yes, I have seen it, but I have to fix the formatting first. Right now, I'm really busy, but I will try to post a new version next week, with this change included.

**Comment by prepare** [comment]
👍 :)

**Comment by Chlumsky** [comment]
It should be fixed now.

**Comment by prepare** [comment]
👍
