### ISSUE TITLE
Compilation error using cmake

### ISSUE THREAD

**Issue by TT5an** [Chlumsky/msdfgen#210]
It prompts that msdfgen-config.h cannot be found. But according to the requirements of base.h, I do not use dynamic linking, so I need to use msdfgen-config.h.
If I define macros in cmake, there will be problems with exporting dll functions.
So, I want to know if there is a good way to use this library directly using cmake.
Thanks！

**Comment by Chlumsky** [comment]
I use the library with CMake all the time without problems, so you have to be more specific. Also, why do you export DLL functions if you don't use dynamic linking?

**Comment by Chlumsky** [comment]
Well, you either need to include MSDFgen's CMakeLists to take care of the configuration, or you have to set the macros yourself (as you mentioned), or you have to make your own msdfgen-config.h file. If you don't do any of that, how is the library supposed to know how you're linking it?

**Comment by TT5an** [comment]
I am sure it‘s using static linking, but why is this macro used?
When I define 'target_compile_definitions(Engine PUBLIC MSDFGEN_PUBLIC=)' in cmake file, the following error will appear.
What is the reason for this? 
I think my question may be stupid. Thank you for your patience!
![image](https://github.com/user-attachments/assets/e64e0136-61af-4714-bfd5-e474f4388e98)

**Comment by Chlumsky** [comment]
Did you actually compile the library source files or did you just include the headers?

My recommendation would be to add MSDFgen to your CMake project like this:

```cmake
add_subdirectory(path/to/msdfgen ${CMAKE_CURRENT_BINARY_DIR}/msdfgen)
target_link_libraries(myTarget PUBLIC msdfgen::msdfgen)
```

Or use vcpkg to build it for you and just link it.

**Comment by TT5an** [comment]
Thank you！I will try your two suggestions. If there are still problems, I will send message again.
