### ISSUE TITLE
Typo in cubic equation solver?

### ISSUE THREAD

**Issue by Parzival-3141** [Chlumsky/msdfgen#211]
My algebra is rusty so I may be misinterpreting, but cross referencing with an explanation of Cardano's formula from [WolframAlpha](https://mathworld.wolfram.com/CubicFormula.html) (specifically figure 73), it seems like there's a typo here where you're subtracting by 2pi instead of 4pi:
https://github.com/Chlumsky/msdfgen/blob/5a88b0c2b95033f7eee826b27c48d399d544d814/core/equation-solver.cpp#L47-L49
```diff
        x[0] = q*cos(1/3.*t)-a;
        x[1] = q*cos(1/3.*(t+2*M_PI))-a;
-       x[2] = q*cos(1/3.*(t-2*M_PI))-a;
+       x[2] = q*cos(1/3.*(t-4*M_PI))-a;
```

**Comment by Chlumsky** [comment]
Yes, it's arbitrary.
