### ISSUE TITLE
Improved anti-aliasing.

### ISSUE THREAD

**Issue by paulhoux** [Chlumsky/msdfgen#22]
Hi Chlumsky,

I noticed some aliasing artifacts when rendering fonts using _msdfgen_. By changing the shader a bit, I was able to improve the rendering quality:

`float sigDist = median( sample.r, sample.g, sample.b );`
`float w = fwidth( sigDist );`
`float opacity = smoothstep( 0.5 - w, 0.5 + w, sigDist );`

Before:
![2016-07-23_130831](https://cloud.githubusercontent.com/assets/304908/17079628/2ba72b4e-5116-11e6-96e9-a867c9671c55.png)

After:
![2016-07-23_130756](https://cloud.githubusercontent.com/assets/304908/17079629/331cf692-5116-11e6-88a5-0a6a50dcb94d.png)

Especially note the capitals "A" and "W". 

Thanks for sharing your hard work on SDF text rendering with the open source community!

**Comment by Chlumsky** [comment]
That shader was just an example that can be used as a quick demonstration. If you're doing something serious you definitely shouldn't use the derivative of the signed distance but of the coordinate instead. The only problem is that then you need to keep track of the range of the distance field to correctly convert it to a 1 pixel thick smoothing. This is the same as with single channel distance fields, so you might be able to find more information about this elsewhere.

**Comment by paulhoux** [comment]
Actually, I think you misunderstood, if I may be so bold. Taking the derivative of the signed distance is actually correct, as it tells you about the rate of change over the span of 1 pixel. In combination with the `smoothstep` function, this results in proper anti-aliasing. You can tell by the difference in quality in the second image. Anyway, I was merely suggesting to update the `README.md` to improve text rendering quality.

**Comment by Chlumsky** [comment]
I'm not saying it is completely incorrect, just not exact. I'm pretty sure it's what causes the weird dots in the corners in your screenshots, but as you wish. Also, unless you're drawing the text in a 3D perspective, I would avoid derivatives completely.

**Comment by paulhoux** [comment]
I believe the dots in the corners are caused by a relatively low size for the glyphs on the texture. The implementation I use ([this one](http://discourse.libcinder.org/t/cinder-sdf-initial-release-wip/171/1)) reserves 32x32 texels by default, which is usually not enough to encode all font details properly. The dots are also visible in the top screenshot, that uses the default shader from the `README.md` file. Thanks for your reply and thanks again for sharing your code.

**Comment by Chlumsky** [comment]
Still try it though, I bet you there won't be any dots if you get rid of fwidth (e.g. replace it with a constant).

**Comment by rougier** [comment]
@paulhoux The `L` letter seems to be better in your version but there are still dots in the corner of the I just before. Also, the hole in the H (third line) seems to have been accentuated.

@Chlumsky Why is there a hole in the H on third line but not on fourth line  ?

**Comment by paulhoux** [comment]
I stand corrected. I tried with an arbitrary constant (in my case 0.15) and the little dots disappeared. This means that taking the `fwidth` of the signed distance is wrong in a theoretical sense. Still, I do believe the minor changes I made to the shader code as presented in the `README.md` do result in better visual quality, even though they technically are incorrect.

From this article, I understand that the right thing to do would be to calculate the distance from the fragment to the glyph outline as measured in pixels. Then use `float opacity = clamp( 0.5 - distanceInPixels, 0.0, 1.0 );` to calculate coverage. The problem is that we only know the distance in _texels_ and we need to convert this value. 

For what it's worth: the following shader code gave me high quality results, even at small scales (zoomed out), but requires an arbitrary multiplication factor that I would like to get rid of:
```
vec3 sample = texture( uTex0, TexCoord ).rgb;
ivec2 sz = textureSize( uTex0, 0 );
float dx = dFdx( TexCoord.x ) * sz.x;
float dy = dFdy( TexCoord.y ) * sz.y;
float toPixels = 8.0 * inversesqrt( dx * dx + dy * dy );
float sigDist = median( sample.r, sample.g, sample.b ) - 0.5;
float opacity = clamp( sigDist * toPixels + 0.5, 0.0, 1.0 );
```

**Comment by behdad** [comment]
Indeed, fwidth() of signed-distance is wrong.  In GLyphy I use:
```
  /* isotropic antialiasing */ 
  vec2 dpdx = dFdx (p); 
  vec2 dpdy = dFdy (p); 
  float m = length (vec2 (length (dpdx), length (dpdy))) * SQRT2_2; 
 
  vec4 color = vec4 (0,0,0,1); 
 
  float gsdist = glyphy_sdf (p, gi.nominal_size GLYPHY_DEMO_EXTRA_ARGS); 
  float sdist = gsdist / m * u_contrast; 
```
where p is the texel coordinate.

**Comment by Michaelangel007** [comment]
> fwidth() of signed-distance is wrong. 

I respectively disagree -- it adds a bit of sharpening. I put together this (shadertoy) demo that clearly shows this:

https://www.shadertoy.com/view/llK3Wm#

I couldn't get the isotropic antialiasing variation to work. :-/

**Comment by paulhoux** [comment]
I don't think your implementation is correct, @Michaelangel007  . The ```smoothstep``` version should not use the range [0.33, 0.66], because this is much too blurry - it should be way tighter. How much tighter is calculated by the ```fwidth()``` function, but as discussed in this issue it should be converted to texel coordinates first, otherwise the results are clearly inferior. See the image I posted for a comparison.

**Comment by Michaelangel007** [comment]
I agree the default smoothstep() needs tweaking.  You can hold down the mouse button and drag it left/right.  At the far left it is equivalent to `a = smoothstep( 0.5, 0.5, d );` which is sharp but then the edges aren't anti-alised.

Thanks for the link. I've added that to the references.

**Comment by Michaelangel007** [comment]
@paulhoux I've added your shader via SMOOTH_2.

Here is a picture of your shader: `float w = fwidth( d ); a = smoothstep( 0.5 - w, 0.5 + w, d );`
![paul_fwidth_smoothstep](https://cloud.githubusercontent.com/assets/7876796/18930139/cd3e76e4-857b-11e6-9f8a-377a85518d06.png)

And here is the one using 1/fwidth() & clamp: `float v = s / fwidth( s ); a = clamp( v + 0.5, 0.0, 1.0 );`
![michael_recip_fwidth_clamp](https://cloud.githubusercontent.com/assets/7876796/18930262/36925156-857c-11e6-822b-c53d5880fc43.png)

If you do a Photoshop Difference on the two images are almost identical. It is almost impossible to visually see any differences between the two.

**Comment by paulhoux** [comment]
Yes, but remember that this is still incorrect and actually has nothing to do with the discussion in this issue. Taking the ```fwidth``` from the texture sample is only part of the solution, as it does not take into account the scale of your glyph in pixels. You're not calculating the distance to the glyph's edge in pixels, but in texels, leading to poor quality rendering when you downscale the glyph. See the link in my previous reply for a proper solution.

@Chlumsky :  I'd also recommend to close this issue, as it is no longer contributing anything to msdfgen.

**Comment by Michaelangel007** [comment]
I don't think anyone is saying the fwidth( texel ) is _mathematically_ correct.  What I _am_ saying that it is certainly _visually_ "good enough" -- the results speak for themselves compared to the proper partial derivatives of the texture coordinates.

In my day job I deal with OpenGL ES on smart TV's and shader complexity is a real ongoing issue -- any wins in optimizations here are VERY noticeable.

In practice there most certainly is a difference between:

* mathematically correct but slow, and
* close enough but very fast.

Truth be told, _most_ of graphics is "one big hack", or I should say "approximations" anyways.

> leading to poor quality rendering when you downscale the glyph. 

In practice I haven't found that to be an issue _at all._  What size is your original SDF font and how small are you down sampling that you found this to be problematic?

I used to use 2 shaders:

* one for downscaling, and
* one for upscaling.

Using the shader I presented above lets me unify them and avoid unnecessary shader loading without general loss of quality for both upscaling and downscaling.  Not everyone is running SDF fonts on a discrete GPU that have spare horsepower to burn. :-/

Granted I'm using a SDF font of around 48 px so that I can have both downsampling and upsampling looking beautiful.

Are there any heuristics for the ratio of the SDF glyphs to actual rendered font height that people are aware of?

**Comment by paulhoux** [comment]
For most fonts I use 64x64 or sometimes 72x72 texels per glyph. This captures the details nicely, unless the font has very thin lines (like e.g. [Parchment](https://s-media-cache-ak0.pinimg.com/originals/59/95/f6/5995f611d701c0db821c13d631e9848b.jpg)). When creating the texture, I use bin-packing to tightly pack the glyphs, so in practice they almost never need to full 72x72 texels. 

I then render text by creating a mesh for the specified font size. This means that for a font size of 12pt, the mesh is actually smaller than 72x72 pixels per glyph and therefor scaling will occur. I want to be able to render 6pt text as well as 480pt text using the same font texture. Here's what it looks like when using a proper shader:

![2016-09-30_205834](https://cloud.githubusercontent.com/assets/304908/19003450/1e6f39d2-8751-11e6-9461-98864325afb5.png)

This is Calibri Light, stored on the texture as 72x72 texels (max) per glyph, then rendered at 15pts. Here's what it looks like when using ```float w = fwidth( sigDist ); float opacity = smoothstep( 0.5 - w, 0.5 + w, sigDist )``` with ```sigDist = median( sample.r, sample.g, sample.b ) - 0.5``` as explained in the MSDFGEN docs:

![2016-09-30_210113](https://cloud.githubusercontent.com/assets/304908/19003516/7d3b9924-8751-11e6-8147-ee2065b61ad1.png)

When zooming in on the text, differences are less pronounced, but you can still see artifacts when using the simple shader:

![2016-09-30_211009](https://cloud.githubusercontent.com/assets/304908/19003809/c159947a-8752-11e6-8df0-e7257d84f4d4.png)

These are gone when using the proper shader:

![2016-09-30_211114](https://cloud.githubusercontent.com/assets/304908/19003818/cc08696e-8752-11e6-9fb1-6b200d0b2a6a.png)

While frame rates are never a great way to compare performance, it's worth pointing out that both shaders run at 318 fps (NVIDIA GTX980M). I have also tested on iOS devices and performance is great there, too. So I'd really recommend using a slightly more complicated shader, because of the much higher quality.
