### ISSUE TITLE
"Failed to load glyph" for specific characters in specific fonts

### ISSUE THREAD

**Issue by arilotter** [Chlumsky/msdfgen#24]
When I try to run msdfgen on the 'o' character (111) with the Proxima Nova font, msdfgen fails with "Failed to load glyph from font file."

Other glyphs from the font work fine, as do other fonts.

**Comment by ryanbartley** [comment]
I also have seen this problem with Helvetica neue lt std. It looks like it pulls out of the inner for loop and resets the `state` variable to NONE and when it resamples `face->glyph->outline.tags[index]`, it comes back with QUADRATIC_POINT and on `state==NONE` it's `REQUIRED(pointType == PATH_POINT)`. I'm looking deeper into it now.

**Comment by ryanbartley** [comment]
I was able to get the 'o' to work after taking out the `REQUIRED(pointType == PATH_POINT)`. Here's the result...
![screen shot 2016-08-18 at 9 56 37 am](https://cloud.githubusercontent.com/assets/2651863/17776315/f68eb9fe-6529-11e6-9c06-d676001d8e59.png)
...I wonder if there's a case that isn't being accounted for, as in a glyph that has a different structure. I will continue researching it. Let me know if that makes sense. [Here's](http://font2s.com/fonts/50691/helvetica_neue_lt_std_75_bold.html#.V7W_dpMrJsY) a link to the font I'm using.

**Comment by Chlumsky** [comment]
Are you using the latest version? There is no line containing `REQUIRE(pointType == PATH_POINT)` anymore.

**Comment by chaoticbob** [comment]
@Chlumsky - Did some digging on this with the latest version of the code. Looks like the letter 'o' in some fonts (e.g. [Neue Helvetica Pro 55 Roman](https://www.fonts.com/font/linotype/neue-helvetica/55-roman) has no PATH_POINT in the first contour in TTF format. So eventually the REQUIRE macro forces it out of the loop with a failure. But if one comments out the REQUIRED macro, an infinite loop occurs due to no exit of the loop.

**Comment by ryanbartley** [comment]
@Chlumsky, I updated and have gotten the 'o' in Helvetica Neue Bold to work, thanks for that. I'm also seeing the same thing as @chaoticbob.

**Comment by chaoticbob** [comment]
Here's my fix for ```loadGlyph``` the issue I mentioned above:
```c++
            switch (state) {
                case NONE:
                    if (pointType == PATH_POINT) {
                        firstPathPoint = index;
                        startPoint = point;
                        state = PATH_POINT;
                    } else if((face->glyph->outline.tags[first] == FT_Curve_Tag_Conic) && (face->glyph->outline.tags[last] == FT_Curve_Tag_Conic)) {
                        firstPathPoint = index;
						Point2 firstPoint( face->glyph->outline.points[first].x/64., face->glyph->outline.points[first].y/64.);
						Point2 lastPoint( face->glyph->outline.points[last].x/64., face->glyph->outline.points[last].y/64.);
						startPoint = .5*(firstPoint + lastPoint);
                        controlPoint[0] = point;						
                        state = QUADRATIC_POINT;
					}
                    break;
```

I found [this discussion](http://stackoverflow.com/questions/3465809/how-to-interpret-a-freetype-glyph-outline-when-the-first-point-on-the-contour-is) to be helpful for contours that are all quadratic points, aka uses the all quadratic shorthand.

**Comment by behdad** [comment]
You should be using `FT_Outline_Decompose()` instead of manually decoding the outline.

**Comment by vkalpias** [comment]
This font also throws that `Failed to load glyph from font file` error  https://fonts.google.com/specimen/Londrina+Solid

**Comment by Chlumsky** [comment]
Alright, I changed it to `FT_Outline_Decompose()` as per @behdad's comment. Everything should be fine now.

**Comment by LautrecOfCarim** [comment]
I'm getting similar problems with some characters. The '$' glyph from [Crimson-Italic](https://www.fontsquirrel.com/fonts/crimson) has overlapping contours and doesn't render properly.

![crimson](https://cloud.githubusercontent.com/assets/8448895/22637363/cfea957e-ec84-11e6-86bd-125cee85c1bb.png)

**Comment by Chlumsky** [comment]
Overlapping contours are not supported unfortunately (see #6). I will try to do something about it when I have time.

**Comment by Chlumsky** [comment]
@LautrecOfCarim This turned out to be a way more complex problem than it seemed inititally, since the contours are supplied in a completely randomized order, but I believe I solved it, so it should work now. It took me two or three afternoons, but it was a very interesting problem. See #6.
