### ISSUE TITLE
Pseudo Distance Field produces Discontinuities

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [Chlumsky/msdfgen#25]
I noticed that the pseudo distance field produces noticeable discontinuities at edges that point towards smooth curves. The issue is probably caused by the call of `distanceToPseudoDistance` afterwards because at the point where the distance fields of the sharp corner and the curve touch each other, only their regular signed distances are equal. Only on the side closer to the sharp corner, the distance field is modified by `distanceToPseudoDistance` changing the value on one side. This creates this discontinuity.

I tried fixing this by moving the call to `distanceToPseudoDistance` inside the inner loop to create the pseudo distance field everywhere instead just for the closest segment. Unfortunately this made things a lot worse and I am not really sure yet why.
An image of a distance field: (Arial)
![brokenedge](https://cloud.githubusercontent.com/assets/18053943/18126385/2997c4d4-6f7b-11e6-9a42-c6867c6dda5c.png)

This is a problem for us because we want to apply shader effects to the rendered font. For that we need proper distance information far away from the glyph itself.

**Comment by Chlumsky** [comment]
I'm aware of this issue, but it didn't seem too serious to me. Unfortunately, fixing it would be much harder than you think. The distance to pseudodistance function call is where it is for a good reason. Here is a paragraph from my thesis that may in part explain your result.

![pdist_problem](https://cloud.githubusercontent.com/assets/18639794/18127401/7cb5d552-6f80-11e6-8363-ddbfd0ff7603.png)

**Comment by QUSpilPrgm** [comment]
Do you have an idea on how to fix it?
I am still not sure that I understand the situation completely.
My first idea would be to check wether there is another curve in between the closest point on each segment and the Pixel P. That might not fix all cases though.

**Comment by behdad** [comment]
In GLyphy I use actual distance to choose the active edge (arc in my case) and only then use pseudo-distance.

**Comment by QUSpilPrgm** [comment]
If I understand correctly, this is exactly what Msdfgen does currently. Unfortunately it produces these discontinuities because the pseudo distance differs from the normal distance right next to it.

**Comment by Chlumsky** [comment]
I know this is a three years old issue, but I recently revisited this project, and managed to solve this problem in the process. Please try the new version 1.6.

Here is a more extreme test case that demonstrates the problem: [monster.zip](https://github.com/Chlumsky/msdfgen/files/3055857/monster.zip)

And here is the difference in generated pseudo-distance field between the old and new version:

![image](https://user-images.githubusercontent.com/18639794/55749801-2533bd80-5a42-11e9-8e1a-c40534a02c24.png)
