### ISSUE TITLE
Font effects implementation

### ISSUE THREAD

**Issue by leavittx** [Chlumsky/msdfgen#27]
Hey, 
This is just a request for more details of how the font effects (outline, soft shadow, thickness) could be implemented in glsl.

I tried to do the outline as follows: 
`fragColor = mix(fragColor, outlineColor, float(abs(sigDist) < 0.1));`
but it's not antialiased in that case of course

**Comment by Chlumsky** [comment]
Alright, [here](https://gist.github.com/Chlumsky/263c960ae0a7df59afc2da4051eb0553) is a [Shadron](https://www.arteryengine.com/shadron/) script that showcases these effects. It's all in the `renderMsdf` function. You will need to know the SDF's pixel range in order to be able to do anti-aliasing correctly, and you may need to increase this range (when generating the SDF) to accomodate for the effects.

**Comment by leavittx** [comment]
Wow, cool stuff. Thanks a lot! Seamlessly ported it to Shadertoy:
https://www.shadertoy.com/view/XtdSRs

Need to improve it a bit before releasing it in public though.

**Comment by torinmb** [comment]
how do you generate a texture with multiple glyphs on it using msdfgen? based off the docs it seems as though you can only generate an image with a single character. Leavittx seems to have been able to combine them into a single image.

**Comment by soimy** [comment]
@torinmb Checkout https://github.com/soimy/msdf-bmfont-xml/

**Comment by torinmb** [comment]
Thanks for the ref @soimy! It looks like @leavittx  somehow managed to pack all the characters in the same order as their ASCII code, and also managed to have each glyph take up the same amount of space, which is very helpful for accessing the image as an atlas in a shader. 
![msdf](https://user-images.githubusercontent.com/6014011/60462486-71446780-9c17-11e9-9526-c7d69512f205.png)

Here's the closest thing I was able to generate. Any help would be greatly appreciated!
![msdfatlas](https://user-images.githubusercontent.com/6014011/60462845-676f3400-9c18-11e9-92a8-3fd5ddaa553f.png)

**Comment by soimy** [comment]
@torinmb [msdf-bmfont-xml](https://github.com/soimy/msdf-bmfont-xml/) uses [maxrects](https://github.com/soimy/maxrects-packer) packing algorithm for maximized efficiency.
Check out the `json` or `fnt` file generated together with the font atlas png files. They include all metric data you need to render your GPU font. Check out the test files for exampe usage by `yarn run render`
Feel free to play around some cli parameters like `--distance-range` `texture-padding` `texture-size` `--smart-size`
