### ISSUE TITLE
Does not compile on MSVC 2015

### ISSUE THREAD

**Issue by TrianglesPCT** [Chlumsky/msdfgen#28]
The include directories are not set up correctly in the default project/solution.

1>c:\depo\common\tools\msdfgen-master\lib\tinyxml2.cpp(24): fatal error C1083: Cannot open include file: 'tinyxml2.h': No such file or directory
1>  lodepng.cpp
1>c:\depo\common\tools\msdfgen-master\lib\lodepng.cpp(31): fatal error C1083: Cannot open include file: 'lodepng.h': No such file or directory
1>  save-png.cpp
1>c:\depo\common\tools\msdfgen-master\ext\save-png.cpp(5): fatal error C1083: Cannot open include file: 'lodepng.h': No such file or directory
1>  import-svg.cpp
1>c:\depo\common\tools\msdfgen-master\ext\import-svg.cpp(5): fatal error C1083: Cannot open include file: 'tinyxml2.h': No such file or directory
1>  import-font.cpp
1>c:\depo\common\tools\msdfgen-master\ext\import-font.cpp(6): fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory

**Comment by Chlumsky** [comment]
I have removed the x64 builds from the solution file, so this shouldn't happen again.
