### ISSUE TITLE
Description for -Printmetrics information

### ISSUE THREAD

**Issue by Xardestros** [Chlumsky/msdfgen#30]
Hi,

could you add a little description, what the output from "-printmetrics" means? Are the values in pixels or Glyph units? What does "bounds" exactly mean? (In my case bounds contains a negative value, which irritates me). What is range?

Basically, my characters are too far apart, when I try to render them as an actual text and im trying to figure out, what Im doing wrong here.

Thanks for your work!

**Comment by Chlumsky** [comment]
The values are in the units of the vector shape. Bounds is the left, bottom, right, and top of the axis-aligned bounding box of the shape. If there's a negative value, that's how the coordinates of the vector shape are defined.

Scale and translate are values that you should normally input yourself (the conversion from vector coordinates to pixel coordinates) but may have been chosen automatically via autoframe. Range (also in shape units) is computed if pixel range is specified or if the default value (pixel range = 2) is kept.

Advance is retrieved from the font, and specifies by how much to shift the point of origin to the right before drawing the next glyph, so I think this is the value you're looking for. It is also in shape coordinates, so you need to multiply by scale to get the value in pixels.
