### ISSUE TITLE
Is it possible to use stb_truetype instead?

### ISSUE THREAD

**Issue by TrianglesPCT** [Chlumsky/msdfgen#31]
The dependency on FreeType(hosted on sourceforge ugh), which appears to have last been compiled on windows 10 years ago is slightly annoying:/

 Does stb_truetype have the capabilities to replace the use of FreeType here?

**Comment by Chlumsky** [comment]
The core of this library only works with vector shapes defined by sequences of line segments and Bézier curves. It is up to you how to get those, and the ability to load them from fonts via FreeType has only been added for convenience. If you have another library that does this then go ahead and use it.
