### ISSUE TITLE
rendering bug

### ISSUE THREAD

**Issue by programmerjake** [Chlumsky/msdfgen#37]
the latest version (8b2d4636) has a rendering error when rendering this svg path.
compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
command line: `./msdfgen -svg shape.svg`

the cyan bar on the far right shouldn't be there.
![output](https://cloud.githubusercontent.com/assets/4584340/23686009/fe0c6818-035b-11e7-8533-38d0b4c22488.png)

render of svg: 
![image](https://cloud.githubusercontent.com/assets/4584340/23686048/38b50768-035c-11e7-8847-f232b646450f.png)

    <svg
       xmlns="http://www.w3.org/2000/svg"
       viewBox="0 0 64 64"
       version="1.1"
       width="64"
       height="64">
     <path
         d="m 51.118496,55.684596 0,-8.665695 -15.010504,0 q -3.077468,5.123513 -8.82417,8.792201 -5.746698,3.668689 -11.587606,4.933753 -0.628056,-2.783142 -3.203078,-4.048209 5.52688,-0.632532 10.457108,-3.257541 4.93023,-2.625009 8.007698,-6.420204 l -9.54643,0 q -2.889052,0 -5.840909,0.126505 0.125607,-1.581331 0,-3.225916 2.951857,0.189762 5.840909,0.189762 l 11.4934,0 q 0.942081,-1.834344 1.318913,-3.731942 l -14.947701,0 q 0.753668,-7.147617 0,-14.295233 l 34.982645,0 q -0.753666,7.147616 -0.0628,14.295233 l -15.638559,0 q -0.314026,1.897598 -1.004887,3.731942 l 17.773946,0 0,12.081369 q 0,1.897598 -1.758553,3.352424 -2.763441,2.150609 -9.169599,2.087355 0.690862,-2.909649 -1.381719,-5.123512 1.884163,0.189758 4.741813,0.221385 2.857649,0.03163 3.10887,-0.221385 0.251222,-0.253014 0.251222,-0.822292 z M 26.687173,17.289874 q 0,-1.707837 -0.125608,-3.225915 l -13.126341,0 0.0628,26.439857 q 0.0628,12.08137 -7.2226217,18.090431 Q 4.9564898,56.443634 2.5070771,55.747848 5.772959,53.85025 7.4059026,50.497829 9.5412869,46.070101 9.2900656,40.503816 l -0.062803,-29.349506 19.5325009,0 0,-2.2138648 q 0,-4.3012187 -0.188418,-8.60243962 2.323803,0.25301302 4.647604,0 Q 33.093342,2.8048823 33.030533,5.271759 l 15.136117,0 q 2.951857,0 5.903714,-0.1265065 -0.188416,1.6445841 0,3.2259145 Q 51.118507,8.2446605 48.16665,8.2446605 l -15.19892,0 0,2.9096495 27.885622,0 0.628057,3.415674 q -0.251223,-0.379519 -0.502444,-0.06325 -1.1305,2.150609 -1.884165,4.617485 l -3.893939,-1.58133 1.381721,-3.478929 -25.62463,0 q -0.125607,1.391573 -0.0628,2.972902 l 14.068425,-0.75904 q 2.700634,-0.189758 5.401268,-0.44277 -0.125607,1.454823 0.125607,2.909649 -2.700634,0.06326 -5.401269,0.18976 l -14.13122,0.759032 q 0.43964,1.707837 1.94697,1.707837 l 16.517836,0 q 1.821358,0 2.260997,-0.885544 l 0.942081,-2.150612 q 1.758555,1.138559 3.768328,1.96085 l -1.884163,3.289171 q -0.628054,1.391571 -2.700633,1.391571 l -18.967252,0 q -2.512219,0 -4.145161,-1.359946 -1.632941,-1.359945 -1.946968,-3.700315 l -6.029325,0.316267 q -2.700635,0.126506 -5.401271,0.442773 0.0628,-1.454826 -0.125607,-2.909649 2.700636,-0.06326 5.338464,-0.18976 z m 12.058647,14.991021 11.304986,0 0,-3.542183 -11.304986,0 0,3.542183 z m -4.207965,0 0,-3.542183 -11.053762,0 0,3.542183 11.053762,0 z m 4.207965,2.656636 0,2.783142 11.242179,0 0,-2.783142 -11.242179,0 z m -4.207965,0 -11.053762,0 0,2.783142 11.053762,0 0,-2.783142 z m 26.943544,-20.367547 0,0.126507 0,-0.126507 z"
         style="fill:#000000" />
    </svg>

**Comment by Chlumsky** [comment]
There seems to be some strange artifact in the SVG:

![svg-artifact](https://cloud.githubusercontent.com/assets/18639794/23695534/08d8ac6e-03e0-11e7-873c-31322cf7fe09.png)

After I removed the strange points in Inkscape, it didn't change the shape and seems to be working:

[shape-fixed.zip](https://github.com/Chlumsky/msdfgen/files/827009/shape-fixed.zip)

What do you think?

**Comment by programmerjake** [comment]
The fixed version appears to be fine to me, however, it would be nice if your program would automatically clean that up as that path comes from one of the fonts installed by default on ubuntu 16.04:
`./msdfgen -font /usr/share/fonts/truetype/wqy/wqy-zenhei.ttc 0x865C`
You could probably fix that by deleting sections of the path that cover zero area.

**Comment by Chlumsky** [comment]
Fixed in the latest version by scanline pass.
