### ISSUE TITLE
Where is "Releases" section?

### ISSUE THREAD

**Issue by PainKKKiller** [Chlumsky/msdfgen#38]
in your docs there is a phrase To start using the program immediately, there is a Windows binary available for download in the "Releases" section. Please can you explain where it ("Releases" section) is located?

**Comment by Chlumsky** [comment]
![releases](https://cloud.githubusercontent.com/assets/18639794/24348980/e4b426f8-12dd-11e7-8de7-68ac2631ac69.png)
