### ISSUE TITLE
Integration with OpenGL side

### ISSUE THREAD

**Issue by HouseOfFinwe** [Chlumsky/msdfgen#39]
Forgive my ignorance, but I'm not sure I quite undrestand how to integrate the SDFs on the OpenGL.  Currently, I have bitmap font engine that renders text from bitmap glyphs generated by freetype.  The fragment shader looks like this:

```
uniform sampler2D bitmap;
in vec2 texC;
in vec4 color;

out vec4 fragColor;

void main(void)
{
	fragColor = texture(tex_bitmap, texC) * vec4(color);
}
```

It enabes alpha blending and uses triangle vertices as a primitive.   Pretty standard stuff.

I tried replacing that shader with your example shader (setting bgColor to the background color and replacing fgColor with color), but all that I see are white squares.

I replaced the standard bitmap atlas with a bitmap atlas generated using your tool to create 64x64 (auto framed) glyphs.

I'm also confused as to how to render the text at a given size (16 pt, 14 pt, etc.).  Is it just a question of scaling the mvp matrix in the vertex shader to get the size that I want?

Any information you could provide as to how things should look on the OpenGL side would be super appreciated.

**Comment by HouseOfFinwe** [comment]
I figured out the issue with the white squares.  It had to do with something the text layout engine was doing to the data channels (since it's not expecting data in the B and G channels).  However, the problem still stands with resizing the text.  The kerning information is for a given font size, and doesn't look right as I scale the mvp matrix.  Additionally, the sizes of the glyphs are not proportional when autoframed.  They get scaled to fix the 64x64 tile, and consequently some lower case letters end up being the same size as their upper case counterparts.  I'm sure I'm missing something.   How do I get each glyph to be scale proportionately?

**Comment by Chlumsky** [comment]
This software generates SDF for individual glyphs but does not help in any way with laying out texture atlases. The autoframe option is meant for preview only and basically says "I don't care about precise positioning, just make my shape nicely fit the output bitmap." To generate a texture atlas, you need to use another library, or manually compute the layout, and pass the appropriate translation and scale values for each glyph. For this, you can utilize the shape metrics that can be outputted.

**Comment by HouseOfFinwe** [comment]
Thank you for you response.  I've gotten past positioning of the shape within the bitmap, using thefont metrics.  I'm using another tool to create the texture atlas.  However,  that tool relies on font metrics based on the size of the font.  In my case, I'm building the fonts from 16 pts.  These then get scaled into the 64x64 tile.  When the layout engine positions the text, it appears monospaced because the glyph bitmaps are 64x64 blocks.  Does the text need to be in blocks?  Can I use the glyph dimensions plus some padding instead of a square, or will this cause issues with the MSDF generation?

**Comment by rougier** [comment]
You can have a look at https://github.com/rougier/freetype-gl. There is an example using (regular) SDF font with proper texture atlas. It might be not so hard to adapt it for msdfgen.

**Comment by HouseOfFinwe** [comment]
Thanks for the suggestion.  I was able to get the all of the spacing issues resolved.  The last remaining issue has to do with the texture borders appearing when I add a drop shadow (based on the font effects shader that Chlumsky posted in a previous issue).  If I add alpha testing to get rid of the these borders, than the shadow disappears, so I'm not sure how to handle them, or why exactly they're appearing in the first place.  I could post a picture if that would help.  It's a light grey thin line around the glyph border on the upper left and top side of the borders.

**Comment by HouseOfFinwe** [comment]
It ended up being the font atlas needed more padding to accommodate the drop shadow offset.  I'll consider the issue closed.  I would, however, appreciate any suggestions about how to maintain the integrity of the glyph when downscaling.  I added some super sampling (a 5 point tent filter) to the fragment shader to help with subpixel rendering, which helps, but I still can't produce a decent looking font at sub 12 pt.
