### ISSUE TITLE
Embedded headers for Freetype may cause issues later

### ISSUE THREAD

**Issue by ckohnert** [Chlumsky/msdfgen#46]
The library headers are currently in the project, but should probably be removed in favor of the package location facilities provided by CMake (it can automatically create the proper CXX flags to locate the exact includes). It's not super urgent as FT doesn't change that frequently, but it could introduce compilation errors later on due to header/library mismatch.

**Comment by Chlumsky** [comment]
OK, i have moved them, so that only the Visual Studio solution uses them.
