### ISSUE TITLE
Proper scaling and positioning confusion.

### ISSUE THREAD

**Issue by kiecker223** [Chlumsky/msdfgen#54]
Hello I am stuck on trying to get this library working, which thank you for writing this library. However getting proper metrics and scaling using the c++ api provided has proved difficult. Can you tell me how I would scale the bitmaps or get proper metrics for rendering?

**Comment by roy-t** [comment]
Did you get it to draw all the glyphs on the correct height (baseline)? See https://github.com/Chlumsky/msdfgen/issues/53 after that you can use libraries like Harfbuzz to figure out kerning and ligatures.

**Comment by kiecker223** [comment]
Thank you for your response but I ended up using Euclidean Distance mapping instead
