### ISSUE TITLE
Problem generating a heart shape

### ISSUE THREAD

**Issue by ill** [Chlumsky/msdfgen#56]
This zip file contains an example svg that results in a weird output.  The svg is produced by exporting from a photoshop file shape I made. 
[HealthIcon.zip](https://github.com/Chlumsky/msdfgen/files/1148108/HealthIcon.zip)

First off, the svg can't be parsed without my pull request: #55

Once done, this is how my Unreal Engine material renders it.

![weirdrender](https://user-images.githubusercontent.com/173169/28208960-3535a8c4-6845-11e7-93af-0f87bbdee59c.png)

This is the output produced by msdfgen when I use the sdf flag.  Not what I'd expect.
![t_ui_healthicon_msdf](https://user-images.githubusercontent.com/173169/28209053-b0938d06-6845-11e7-9cb9-b8fc37706ce0.png)

There may be some weirdness in my shape data.  I'll look at trying to fix the shape later.

**Comment by ill** [comment]
I managed to get a better render by redoing my shape a bit
[HealthIcon.zip](https://github.com/Chlumsky/msdfgen/files/1148203/HealthIcon.zip)

I get this line down the middle now at some scales.
![hardline](https://user-images.githubusercontent.com/173169/28210204-1fd857b4-684b-11e7-8265-ded3ccc47631.png)

It looks better if I generate a regular signed distance field and use my grayscale sdf shader instead of the multichannel one, but there's that weird artifact that occurs that your algorithm solves.


.

**Comment by Chlumsky** [comment]
The first issue was a bug in the SVG parser which I have now fixed.

The second one is a little more complicated than it may seem. This is actually a specific edge case, where at the middle vertex, the inner angle between the two curves is exactly 360 degrees. The simplest solution would be to move the curve control points ever so slightly away from the middle to decrease this angle.

**Comment by fire** [comment]
I tested the latest and the change on https://github.com/Chlumsky/msdfgen/commit/82364f92ecfc8d7282dc746363d976144953d7c0 seemed to solve the problem. Will do some more testing.

Repeated.

**Comment by Chlumsky** [comment]
This issue should be resolved by 80039d7ed6c275f381eeaface5378c02870fe462, the fix is present in the v1.8 release.
