### ISSUE TITLE
Compiling on MacOS

### ISSUE THREAD

**Issue by neurolabusc** [Chlumsky/msdfgen#57]
Hello- 
 It is great that the releases include a compiled Windows executable. As a feature request, can the documentation be extended to include instructions for how to compile the comprehensive standalone console program on other distributions. The naive `g++ -o ms main.cpp` does not work on MacOS. There is a precompiled executable for [MacOS](https://github.com/Jam3/msdf-bmfont), but it does not appear to be a recent version. Thanks for a terrific program.

**Comment by ckohnert** [comment]
You should be able to use CMake after checking out the code:
```
mkdir out
cd out && cmake .. && make
```
It requires truetype libraries to build (it will complain if it can't find them). Both CMake and Truetype development libs can easily be obtained using [homebrew](https://brew.sh/).

**Comment by neurolabusc** [comment]
Terrific, that works. As a feature request, would be great to include this in the README.md

**Comment by Chlumsky** [comment]
Added mention in Readme.
