### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by bjornbytes** [Chlumsky/msdfgen#58]
Is there any interest in adding a C API?  I'm working on an engine written in C that uses this library and have a rudimentary C API for msdfgen in a fork.  If there's interest, I could clean it up and open up a PR.

**Comment by TannerRogalsky** [comment]
@bjornbytes I'd be interested in that. Would make it nicer to use with LuaJIT's FFI in Love.

**Comment by exezin** [comment]
If anyone is still looking for a C API, I've been working on a pure C implementation of this for the past few weeks for my own C-based game engine.

It's still a bit buggy and has some work to do, but overall its working pretty well and at the very least could be used as a reference for someone else trying to implement this in C.  It has zero external depends as it only relies on stb_truetype.h (which is included) to load the TTF.

https://githubcom/exezin/msdf-c

**Comment by bjornbytes** [comment]
Great!  I'm going to close this issue since it's been a while and the above implementation is available now.

**Comment by radgeRayden** [comment]
The implementation linked is no longer available.
