### ISSUE TITLE
A lot of artifacts when processing Chineese fonts

### ISSUE THREAD

**Issue by dimozaprianov** [Chlumsky/msdfgen#59]
Trying to process this font [FandolKai.zip](https://github.com/Chlumsky/msdfgen/files/1248533/FandolKai.zip) produces a lot of artifacts. Here is one example I studied more carefully
![char_36864](https://user-images.githubusercontent.com/1011810/29663047-146cd1e6-88d2-11e7-8a64-6770a341b5bf.png) - char #36864
![char_36873](https://user-images.githubusercontent.com/1011810/29663370-6defb8d6-88d3-11e7-8770-4603eee70764.png) - char #36873

**Comment by programmerjake** [comment]
possibly related: #37

**Comment by Chlumsky** [comment]
Please try out [ckohnert's fork](https://github.com/ckohnert/msdfgen), he's fixing many of these artifacts.

**Comment by Chlumsky** [comment]
Should be fixed in the latest version by scanline pass.
