### ISSUE TITLE
Self-intersecting shapes

### ISSUE THREAD

**Issue by Chlumsky** [Chlumsky/msdfgen#6]
The program does not support shapes whose edge segments intersect each other. Unfortunatelly, I have found that some font glyphs, especially those with accents, are defined like this.

This could be solved either by preprocessing the shape to eliminate such occurences, or perhaps by generating multiple distance fields for non-intersecting components (contours), and combining them in a certain way. The latter solution should be sufficient for the accents.

**Comment by behdad** [comment]
We do the latter in GLyphy, though that's in a branch from three years ago that I have not merged yet...

**Comment by Chlumsky** [comment]
Overlapping contours resolved in 0e68504f44ad156b8e73773d056a98c8dfdc61db.
