### ISSUE TITLE
Shape::bounds should initialize returns

### ISSUE THREAD

**Issue by gigadude** [Chlumsky/msdfgen#64]
Just spent a while debugging nondeterministic results from `Shape::bounds()`, it could be improved with:

```c++
void Shape::bounds(double &l, double &b, double &r, double &t) const {
    l = b = LARGE_VALUE;
    r = t = -LARGE_VALUE;
    for (std::vector<Contour>::const_iterator contour = contours.begin(); contour != contours.end(); ++contour)
        contour->bounds(l, b, r, t);
}
```

**Comment by Chlumsky** [comment]
Sorry, but this is a design choice, to be consistent with `Contour` and `EdgeSegment` and allow to compute the combined bounds of multiple shapes. This has now been clarified in the function's description.
