### ISSUE TITLE
Mismatch between paper and code

### ISSUE THREAD

**Issue by Kaisha** [Chlumsky/msdfgen#65]
I've been reading through your paper in an attempt to integrate multi-channel SDFs into a C++ font handling library I wrote; and came across a small discrepancy between the paper and your code.

In the file edge-segments.cpp, function SignedDistance QuadraticSegment::signedDistance(Point2 origin, double &param) const, you have:

    Vector2 qa = p[0]-origin;
    Vector2 ab = p[1]-p[0];
    Vector2 br = p[0]+p[2]-p[1]-p[1];
    double a = dotProduct(br, br);
    double b = 3*dotProduct(ab, br);
    double c = 2*dotProduct(ab, ab)+dotProduct(qa, br);
    double d = dotProduct(qa, ab);

This slightly different from the equations in your paper on page 16, notably 2.31 and 2.38.  If I'm reading the paper right what you should have is:

Vector2 qa = origin-p[0];
double c = 2*dotProduct(ab, ab)-dotProduct(br, qa);
double d = -dotProduct(qa, ab);

Now the negation of qa (from p - p0 to p0 - p) is balanced by the negations in c and d.  So the end result is mathematically identical.  I'm wondering, was this intentional?  Is there some reason for this change that I'm not seeing?

**Comment by Chlumsky** [comment]
There is no meaningful difference. I probably had a change of heart which variant I thought was more elegant, I tend to overthink these things sometimes. It's definitely the one in the code by the way. :)

**Comment by Kaisha** [comment]
Thank-you for the prompt response.  I completely understand, I just wanted to be sure I wasn't missing some subtle implication.
