### ISSUE TITLE
Artefacts with applying effects on certain letters

### ISSUE THREAD

**Issue by Rhumage** [Chlumsky/msdfgen#67]
When I apply an outline to E and H and some other letters with other fonts, I get artefacts like this:

![image](https://user-images.githubusercontent.com/1548218/38252072-7c67e1ac-3753-11e8-8a75-38e4464ad500.png)

**Comment by Chlumsky** [comment]
Keep in mind that this is an approximate rendering method, and it is designed to be most precise at glyph edges. The further away from an edge, the higher the probability that the distance is not evaluated precisely, resulting in an artifact such as this one. This may be mitigated by increasing the distance field density.

**Comment by neurolabusc** [comment]
I am experiencing similar issues with msdf-atlas-gen version 1.9. I believe this is a regression, as I can render fonts created with prior versions without these artefacts. The screenshot below shows the issue with a screenPxRange of 1.8000001907348633. Note the `n` and `u`. These artefacts appear and dissappear depending as the image grows and shrinks (e.g. not all screenPxRange values).

You can replicate my images with:

```
msdf-atlas-gen.exe -font Roboto-Regular.ttf -charset chars.txt -pxrange 2 -dimensions 256 256 -format png -json fnt.json -imageout fnt.png
```
Where chars.txt is a text file with the following characters

```
"\"\\ ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!`?'.,;:()[]{}<>|/@^$-%+=#_&~*"
```

![artefact](https://user-images.githubusercontent.com/8930807/124938307-2fa0e100-dfd6-11eb-9934-6042f990c620.png)

**Comment by neurolabusc** [comment]
The issue can also be observed by looking at the bitmaps created by the new (defective) and prior (good) versions (generated with same commands as above, but with `-dimensions 512 256`. Note that two colors touch at full brightness (255) in the new version.

Prior versions:

![good](https://user-images.githubusercontent.com/8930807/124940870-56f8ad80-dfd8-11eb-8dff-146445a3817c.png)

Latest version:
![bad](https://user-images.githubusercontent.com/8930807/124940886-59f39e00-dfd8-11eb-878d-2ed29b0ea370.png)

**Comment by Chlumsky** [comment]
@neurolabusc You are right that this is a new regression and it would seem that I've made an embarassing mistake in the new error correction algorithm, which should now be fixed by 35caf383783886918aa6013b7949956065a42e19. Please try it out and let me know if there are still problems, if not I will release a hotfix version.

**Comment by neurolabusc** [comment]
@Chlumsky  thanks for the quick response. I will not have access to a development system for the next week. Is it possible that you could share a compiled copy - macOS, Linux or Windows would be fine. You could even use the "pre-release" function for Github releases to let users test your fix.

**Comment by Chlumsky** [comment]
@neurolabusc Alright, I have published the pre-release, so you can test it.

**Comment by neurolabusc** [comment]
1. The pre-release resolves my regression issue.
2. I suggest you close this issue, as the original issue can be resolved by generating the recent RGBA [MTSDF](https://github.com/Chlumsky/msdf-atlas-gen) textures.
3. I only tested the 32-bit application, as Windows 10 rejected the 64-bit pre-release claiming it exhibits the `Wacatac.B!ml` script virus. I suspect this is a false alarm, but it might be nice to see if the 64-bit version can be packaged in such a way to avoid this issue.
