### ISSUE TITLE
Issue using the program.

### ISSUE THREAD

**Issue by KakCAT** [Chlumsky/msdfgen#68]
Hello,

all fonts I'm trying (tried 6 so far) are having an artifact on the side that touches bottom-left (it's hard to explain but easy to see). Also the output.png file does not cover the full PNG, but 1/4 of the image, which seems weird although I only have the example.bat defineshape as reference.

The commandline I'm using is, in example,: msdfgen.exe -font arial.ttf 65 -testrender render.png 1024 1024

I've tried binaries 1.4, 1.5 and compiled the https://github.com/ckohnert/msdfgen fork. All give me this problem.

In example, J is verdana, C is ConsolasBold, A is Arial (for arial the problem is minimal , at the bottom left, but still is there).

Any ideas?
Thanks!

![outputa](https://user-images.githubusercontent.com/2372854/45920918-a6af6e00-beab-11e8-929e-3f5b1d37a5ff.png)
![rendera](https://user-images.githubusercontent.com/2372854/45920919-a7480480-beab-11e8-9826-80baa481f6b1.png)
![output](https://user-images.githubusercontent.com/2372854/45920928-b29b3000-beab-11e8-85e0-8b4d8f84bb52.png)
![render](https://user-images.githubusercontent.com/2372854/45920929-b29b3000-beab-11e8-9085-889dcd7d7678.png)

![outputj](https://user-images.githubusercontent.com/2372854/45920908-88e20900-beab-11e8-9a42-df3c283d4b6e.png)
![renderj](https://user-images.githubusercontent.com/2372854/45920909-88e20900-beab-11e8-919a-61cb025927fc.png)

**Comment by programmerjake** [comment]
the artifacts are caused by the character being too close to the edge of the image.

**Comment by KakCAT** [comment]
thanks, I found out that with -autoframe all results seem to be OK now.
