### ISSUE TITLE
"Fatter" fonts

### ISSUE THREAD

**Issue by KakCAT** [Chlumsky/msdfgen#69]
I'd love to use MSDF fonts (btw, kudos  and thanks for the program/library) but font outlining is a must for the project I'd be using them.

Unfortunately the shaders I've seen with SDF outlines are very weak: artifacts and swiggly lines, specially when having to use pronunciated outlines.

So my idea is using two MSDF fonts instead of one: one for the outline (a "fatter" version of the font) and the usual font. Print first the outline and then the normal font (or maybe using two textures in the shader and do it in one pass)

And here comes the question: Is it possible/easy to create a fatter version of the font with msdfgen without the obvious loss of quality the MSDF outline shaders present? Could somebody give some pointers on what should be modified in the code to obtain that?

Thanks!

**Comment by Chlumsky** [comment]
Could you provide an example of the problem? Maybe you have the wrong shaders.

In any case, you cannot generate SDF for a "fatter" version of the font with this software, you'd have to use something else to modify the geometry.

**Comment by Rhumage** [comment]
It's probably the same issue as I had in #67.

What is the best way to calculate distance field in shaders? This is how I do it at the moment:

```
	uvec2 sz = PXRANGE / textureSize(msdfa, 0).xy;
	float dx = dFdx(texCoords.x) * sz.x;
	float dy = dFdy(texCoords.y) * sz.y;
	float toPixels = 8 * inversesqrt(dx * dx + dy * dy);
	return clamp(dist * toPixels + 0.5f, 0.0f, 1.0f);
```

**Comment by KakCAT** [comment]
Hi,

sorry for the delay. I thought it wasn't the same problem as #67 (that's why I opened a new issue) but actually it was the same indeed. Increasing pxrange and a little bit the texture resolution fixed the problem

I was using the shadron example for MSDF + border + shadows.

thanks to both.

**Comment by KakCAT** [comment]
> Can you tell me what texture resolution and px range you're using?
> 
> And can you link me to the code for the example you mention?

sure. I moved from 32x32 to 48x48 and used pxrange 6. Font is arial.ttf (I used for a test) but I suppose that size, pxrange depends on font and amount of border.

shader:

https://gist.github.com/Chlumsky/263c960ae0a7df59afc2da4051eb0553

**Comment by Rhumage** [comment]
Thank you so much!
