### ISSUE TITLE
MSDF error detection may fail inside thin features

### ISSUE THREAD

**Issue by Chlumsky** [Chlumsky/msdfgen#7]
The error detection/correction of the multi-channel distance field is based on identification of "fronts of discontinuity" in the distance field, but they may not be correctly detected if they are too close to an edge to be sufficiently "pronounced", and the change in the distance field seems completely smooth. This may cause visual artifacts in rare cases, where distance field resolution is insufficient.

The problem can be reproduced like this:

```
msdfgen.exe -font FreeSansBold.ttf 'A' -size 16 16 -autoframe
```

![render](https://cloud.githubusercontent.com/assets/18639794/14879378/3f48bfea-0d29-11e6-81b9-fdfb3e1343fa.png)

I have an idea how to fix this by generating a gradient vector field of the signed distances, and using that in the error detection.

**Comment by rougier** [comment]
Maybe this is related to your problem:

https://lambdacube3d.wordpress.com/2014/11/12/playing-around-with-font-rendering/
(see artifact resulting from linear interpolation)

**Comment by Chlumsky** [comment]
Yes, that is exactly the same kind of artifact. I also had an illustration of this phenomenon in my thesis:

![interpolation_errors](https://cloud.githubusercontent.com/assets/18639794/14886824/252c3d9c-0d53-11e6-8388-721af1115016.png)

The thing is, I am already detecting when this happens in [msdfErrorCorrection](../tree/master/core/msdfgen.cpp#L93), but in some special cases, where several edges occupy a very small area of the distance field, the detection fails.

**Comment by mchiasson** [comment]
sounds like what I am getting with this character:
```
msdfgen msdf -font DejaVuSansMono.ttf 231 -o msdf.png -size 64 64 -testrender render.png 1024 1024
```
which is giving me this: ![render](https://cloud.githubusercontent.com/assets/961637/19139788/8c8a7334-8b55-11e6-870f-771fdfa26ac1.png)

**Comment by Chlumsky** [comment]
No, that looks like issue #6.

**Comment by mchiasson** [comment]
ohhh! I see! there are 2 pieces and they overlapped. Makes sense. I can re-post this image in #6 if you'd like an example.
