### ISSUE TITLE
Compiling on Ubuntu x86_64

### ISSUE THREAD

**Issue by ghost** [Chlumsky/msdfgen#71]
There is a small problem that can be fixed easily when compiling the msdfgen executable on linux,
following these steps:
```git clone MyDir ```
`cd MyDir && mkdir build && cd build `
`cmake .. && make VERBOSE=1 `
lib_msdfgen is built successfully, but as one tries to link the CXX executable msdfgen, one gets the following undefined references.
> [100%] Linking CXX executable msdfgen
> /usr/bin/cmake -E cmake_link_script CMakeFiles/msdfgen.dir/link.txt --verbose=1
> /usr/bin/c++   -std=c++11 -O3 -DNDEBUG  -rdynamic CMakeFiles/msdfgen.dir/main.cpp.o  -o msdfgen libmsdfgen.a /usr/local/lib/libfreetype.a 
> /usr/local/lib/libfreetype.a(sfnt.c.o): In function `error_callback':
> sfnt.c:(.text+0x218): undefined reference to `png_get_error_ptr'
> sfnt.c:(.text+0x241): undefined reference to `png_set_longjmp_fn'
> /usr/local/lib/libfreetype.a(sfnt.c.o): In function `read_data_from_FT_Stream':
> sfnt.c:(.text+0x27d): undefined reference to `png_get_io_ptr'
> sfnt.c:(.text+0x2b1): undefined reference to `png_get_error_ptr'
> sfnt.c:(.text+0x2d0): undefined reference to `png_error'
> /usr/local/lib/libfreetype.a(sfnt.c.o): In function `Load_SBit_Png':
> sfnt.c:(.text+0x44a): undefined reference to `png_create_read_struct'
> sfnt.c:(.text+0x47b): undefined reference to `png_create_info_struct'
> sfnt.c:(.text+0x4ab): undefined reference to `png_destroy_read_struct'
> sfnt.c:(.text+0x4ce): undefined reference to `png_set_longjmp_fn'
> sfnt.c:(.text+0x506): undefined reference to `png_set_read_fn'
> sfnt.c:(.text+0x51c): undefined reference to `png_read_info'
> sfnt.c:(.text+0x55b): undefined reference to `png_get_IHDR'
> sfnt.c:(.text+0x670): undefined reference to `png_set_palette_to_rgb'
> sfnt.c:(.text+0x689): undefined reference to `png_set_expand_gray_1_2_4_to_8'
> sfnt.c:(.text+0x6a4): undefined reference to `png_get_valid'
> sfnt.c:(.text+0x6b7): undefined reference to `png_set_tRNS_to_alpha'
> sfnt.c:(.text+0x6d1): undefined reference to `png_set_strip_16'
> sfnt.c:(.text+0x6eb): undefined reference to `png_set_packing'
> sfnt.c:(.text+0x70f): undefined reference to `png_set_gray_to_rgb'
> sfnt.c:(.text+0x728): undefined reference to `png_set_interlace_handling'
> sfnt.c:(.text+0x741): undefined reference to `png_set_filler'
> sfnt.c:(.text+0x757): undefined reference to `png_read_update_info'
> sfnt.c:(.text+0x796): undefined reference to `png_get_IHDR'
> sfnt.c:(.text+0x7f8): undefined reference to `png_set_read_user_transform_fn'
> sfnt.c:(.text+0x810): undefined reference to `png_set_read_user_transform_fn'
> sfnt.c:(.text+0x930): undefined reference to `png_read_image'
> sfnt.c:(.text+0x964): undefined reference to `png_read_end'
> sfnt.c:(.text+0x988): undefined reference to `png_destroy_read_struct'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_face_globals_new':
> autofit.c:(.text+0x4747): undefined reference to `hb_ft_font_create'
> autofit.c:(.text+0x4757): undefined reference to `hb_buffer_create'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_face_globals_free':
> autofit.c:(.text+0x48bf): undefined reference to `hb_font_destroy'
> autofit.c:(.text+0x48cf): undefined reference to `hb_buffer_destroy'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_shaper_get_coverage':
> autofit.c:(.text+0xf689): undefined reference to `hb_font_get_face'
> autofit.c:(.text+0xf6ea): undefined reference to `hb_ot_tags_from_script'
> autofit.c:(.text+0xf74a): undefined reference to `hb_set_create'
> autofit.c:(.text+0xf776): undefined reference to `hb_ot_layout_collect_lookups'
> autofit.c:(.text+0xf782): undefined reference to `hb_set_is_empty'
> autofit.c:(.text+0xf78f): undefined reference to `hb_set_create'
> autofit.c:(.text+0xf7c8): undefined reference to `hb_ot_layout_lookup_collect_glyphs'
> autofit.c:(.text+0xf7df): undefined reference to `hb_set_next'
> autofit.c:(.text+0xf7e8): undefined reference to `hb_set_create'
> autofit.c:(.text+0xf814): undefined reference to `hb_ot_layout_collect_lookups'
> autofit.c:(.text+0xf819): undefined reference to `hb_set_create'
> autofit.c:(.text+0xf852): undefined reference to `hb_ot_layout_lookup_collect_glyphs'
> autofit.c:(.text+0xf869): undefined reference to `hb_set_next'
> autofit.c:(.text+0xf98c): undefined reference to `hb_ot_layout_lookup_would_substitute'
> autofit.c:(.text+0xf9a9): undefined reference to `hb_set_next'
> autofit.c:(.text+0xf9fe): undefined reference to `hb_set_subtract'
> autofit.c:(.text+0xfa6b): undefined reference to `hb_set_next'
> autofit.c:(.text+0xfa84): undefined reference to `hb_set_destroy'
> autofit.c:(.text+0xfa90): undefined reference to `hb_set_destroy'
> autofit.c:(.text+0xfa9c): undefined reference to `hb_set_destroy'
> autofit.c:(.text+0xfaa8): undefined reference to `hb_set_destroy'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_shaper_buf_create':
> autofit.c:(.text+0xfad4): undefined reference to `hb_buffer_create'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_shaper_buf_destroy':
> autofit.c:(.text+0xfaf2): undefined reference to `hb_buffer_destroy'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_shaper_get_cluster':
> autofit.c:(.text+0xfb97): undefined reference to `hb_font_set_scale'
> autofit.c:(.text+0xfc6d): undefined reference to `hb_buffer_clear_contents'
> autofit.c:(.text+0xfc8b): undefined reference to `hb_buffer_add_utf8'
> autofit.c:(.text+0xfc97): undefined reference to `hb_buffer_guess_segment_properties'
> autofit.c:(.text+0xfcb6): undefined reference to `hb_shape'
> autofit.c:(.text+0xfcdd): undefined reference to `hb_buffer_clear_contents'
> autofit.c:(.text+0xfcfb): undefined reference to `hb_buffer_add_utf8'
> autofit.c:(.text+0xfd07): undefined reference to `hb_buffer_guess_segment_properties'
> autofit.c:(.text+0xfd21): undefined reference to `hb_shape'
> autofit.c:(.text+0xfd34): undefined reference to `hb_buffer_get_glyph_infos'
> autofit.c:(.text+0xfd4b): undefined reference to `hb_buffer_get_glyph_infos'
> autofit.c:(.text+0xfdc3): undefined reference to `hb_buffer_clear_contents'
> autofit.c:(.text+0xfdcf): undefined reference to `hb_buffer_get_length'
> /usr/local/lib/libfreetype.a(autofit.c.o): In function `af_shaper_get_elem':
> autofit.c:(.text+0xfe39): undefined reference to `hb_buffer_get_glyph_infos'
> autofit.c:(.text+0xfe50): undefined reference to `hb_buffer_get_glyph_positions'
> /usr/local/lib/libfreetype.a(ftgzip.c.o): In function `ft_gzip_file_init':
> ftgzip.c:(.text+0x377): undefined reference to `inflateInit2_'
> /usr/local/lib/libfreetype.a(ftgzip.c.o): In function `ft_gzip_file_done':
> ftgzip.c:(.text+0x3bd): undefined reference to `inflateEnd'
> /usr/local/lib/libfreetype.a(ftgzip.c.o): In function `ft_gzip_file_reset':
> ftgzip.c:(.text+0x48a): undefined reference to `inflateReset'
> /usr/local/lib/libfreetype.a(ftgzip.c.o): In function `ft_gzip_file_fill_output':
> ftgzip.c:(.text+0x6da): undefined reference to `inflate'
> /usr/local/lib/libfreetype.a(ftgzip.c.o): In function `FT_Gzip_Uncompress':
> ftgzip.c:(.text+0xe55): undefined reference to `inflateInit2_'
> ftgzip.c:(.text+0xe7f): undefined reference to `inflate'
> ftgzip.c:(.text+0xe9a): undefined reference to `inflateEnd'
> ftgzip.c:(.text+0xec9): undefined reference to `inflateEnd'
> collect2: error: ld returned 1 exit status
> CMakeFiles/msdfgen.dir/build.make:96: recipe for target 'msdfgen' failed
> make[2]: *** [msdfgen] Error 1

This can be easily fixed by manually running:
``` /usr/bin/c++   -std=c++11 -O3 -DNDEBUG  -rdynamic CMakeFiles/msdfgen.dir/main.cpp.o  -o msdfgen libmsdfgen.a `freetype-config --static --libs` /usr/local/lib/libfreetype.a ```

Instead of cmake running:
``` /usr/bin/c++   -std=c++11 -O3 -DNDEBUG  -rdynamic CMakeFiles/msdfgen.dir/main.cpp.o  -o msdfgen libmsdfgen.a /usr/local/lib/libfreetype.a ```

**Comment by ckohnert** [comment]
Hm, is there any chance you've got multiple versions of freetype installed and cmake is picking up the wrong one somehow? I'm pretty sure cmake is adding the /usr/local/lib/libfreetype.a which I believe it is supposed to get from calling the script you're using.

**Comment by IhdeneMalek** [comment]
Calling freetype-config yields -lfreetype -lpng16 -lm -lz -lm -lz. To my knowledge, the repository is using an old version of freetype, and I encountered this page of information on my search to a fix: https://bugzilla.mozilla.org/show_bug.cgi?id=986008

**Comment by ckohnert** [comment]
Calling `freetype-config --static --libs` gives those results? That's what CMake should be using if you're building static, I'm pretty sure.

**Comment by Chlumsky** [comment]
CMake build has been reworked in 31dda2d47417b8999b9c873d642fba9a30cd2f9d, please reopen if the issue persists.

**Comment by maltaisn** [comment]
I'm still experiencing this issue on Ubuntu 20.04, with similar output as @ghost. I've been at it for a few hours but I just can't make it work. FreeType was built and installed without issues (version 2.10.4).
```text
[ 96%] Building CXX object CMakeFiles/msdfgen-standalone.dir/main.cpp.o
[100%] Linking CXX executable msdfgen
/usr/bin/ld: /usr/local/lib/libfreetype.a(sfnt.c.o): in function `error_callback':
sfnt.c:(.text+0x22a): undefined reference to `png_get_error_ptr'
/usr/bin/ld: sfnt.c:(.text+0x253): undefined reference to `png_set_longjmp_fn'
/usr/bin/ld: /usr/local/lib/libfreetype.a(sfnt.c.o): in function `read_data_from_FT_Stream':
sfnt.c:(.text+0x297): undefined reference to `png_get_io_ptr'
/usr/bin/ld: sfnt.c:(.text+0x2cb): undefined reference to `png_get_error_ptr'
/usr/bin/ld: sfnt.c:(.text+0x2ea): undefined reference to `png_error'
/usr/bin/ld: /usr/local/lib/libfreetype.a(sfnt.c.o): in function `Load_SBit_Png':
sfnt.c:(.text+0x467): undefined reference to `png_create_read_struct'
/usr/bin/ld: sfnt.c:(.text+0x498): undefined reference to `png_create_info_struct'
/usr/bin/ld: sfnt.c:(.text+0x4c8): undefined reference to `png_destroy_read_struct'
/usr/bin/ld: sfnt.c:(.text+0x4eb): undefined reference to `png_set_longjmp_fn'
/usr/bin/ld: sfnt.c:(.text+0x527): undefined reference to `png_set_read_fn'
/usr/bin/ld: sfnt.c:(.text+0x53d): undefined reference to `png_read_info'
/usr/bin/ld: sfnt.c:(.text+0x57c): undefined reference to `png_get_IHDR'
/usr/bin/ld: sfnt.c:(.text+0x690): undefined reference to `png_set_palette_to_rgb'
/usr/bin/ld: sfnt.c:(.text+0x6a9): undefined reference to `png_set_expand_gray_1_2_4_to_8'
/usr/bin/ld: sfnt.c:(.text+0x6c4): undefined reference to `png_get_valid'
/usr/bin/ld: sfnt.c:(.text+0x6d7): undefined reference to `png_set_tRNS_to_alpha'
/usr/bin/ld: sfnt.c:(.text+0x6f1): undefined reference to `png_set_strip_16'
/usr/bin/ld: sfnt.c:(.text+0x70b): undefined reference to `png_set_packing'
/usr/bin/ld: sfnt.c:(.text+0x72f): undefined reference to `png_set_gray_to_rgb'
/usr/bin/ld: sfnt.c:(.text+0x748): undefined reference to `png_set_interlace_handling'
/usr/bin/ld: sfnt.c:(.text+0x761): undefined reference to `png_set_filler'
/usr/bin/ld: sfnt.c:(.text+0x777): undefined reference to `png_read_update_info'
/usr/bin/ld: sfnt.c:(.text+0x7b6): undefined reference to `png_get_IHDR'
/usr/bin/ld: sfnt.c:(.text+0x818): undefined reference to `png_set_read_user_transform_fn'
/usr/bin/ld: sfnt.c:(.text+0x830): undefined reference to `png_set_read_user_transform_fn'
/usr/bin/ld: sfnt.c:(.text+0x950): undefined reference to `png_read_image'
/usr/bin/ld: sfnt.c:(.text+0x984): undefined reference to `png_read_end'
/usr/bin/ld: sfnt.c:(.text+0x9a8): undefined reference to `png_destroy_read_struct'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/msdfgen-standalone.dir/build.make:91: msdfgen] Error 1
make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/msdfgen-standalone.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Any idea on how to fix it?

**Comment by Chlumsky** [comment]
Build FreeType without PNG support or link LibPNG.

**Comment by maltaisn** [comment]
Thanks it works.
