### ISSUE TITLE
Error with letter Ç

### ISSUE THREAD

**Issue by Rhumage** [Chlumsky/msdfgen#73]
Trying to generate letter Ç (unicode 199) doesn't work correctly.
The inside is empty while it draws something outside. 
![2](https://user-images.githubusercontent.com/1548218/55404204-ae855480-5557-11e9-90d0-394bcdeb2e99.png)

**Comment by Chlumsky** [comment]
Even though you provided no data that would allow me to reproduce the issue, from looking at the output, it seems that the font you're using has overlapping contours with completely random winding directions. The MSDFGEN library only works correctly if *valid* input is supplied.

You may also want to try [ckohnert's fork](/ckohnert/msdfgen), which I believe contains code that handles some non-standard cases like this.

**Comment by Rhumage** [comment]
I am using this ttf: https://www.1001fonts.com/titan-one-font.html#character-map
And my command: msdfgen.exe msdf -font TitanOne-Regular.ttf 199 -size 64 64 -pxrange 20 -scale 2  -o 5.png -autoframe

**Comment by Rhumage** [comment]
Is there anything I can do to make it valid or is the issue within the ttf?

**Comment by Chlumsky** [comment]
It's an issue withing the TTF. The top part of the shape has the opposite winding than the bottom part, even though they should be the same. The library requires these to be consistent for it to work properly. You can see that the glyph is not rendered properly even on the website you linked (notice the white gap):
![image](https://user-images.githubusercontent.com/18639794/55408117-a7fadb00-555f-11e9-888a-1a9bcbe631d4.png)

You can make it valid by implementing some kind of preprocessing of the vector path, or maybe fixing the font in an editor.

**Comment by Rhumage** [comment]
Ok, thank you.
