### ISSUE TITLE
[Feature suggestion] inside / outside bias parameter

### ISSUE THREAD

**Issue by gregee123** [Chlumsky/msdfgen#76]
Would you be willing to introduce a range bias param so that we can have more than 128 shades on the outside of the outline? Inside is usually too narrow to make use of 128 shades anyway.

Granted that would require passing another parameter to the shader additional outside range could be worth it.

**Comment by Chlumsky** [comment]
I mean, sure, but do you really need me to do it? The values are represented as full unclamped floating-point numbers up until the point they are saved to a PNG, so it's just a matter of adding or subtracting a constant to each value in the bitmap before that.

Or, even if you just use the compiled binary, you can output the floating point data (`-format binfloat`) and reprocess it using a separate script.

**Comment by Chlumsky** [comment]
Implemented in 9d5c7c54e8f28bcd3756fffd5a096e2604b97102 as `-distanceshift`.
