### ISSUE TITLE
Converting all glyphs of a font

### ISSUE THREAD

**Issue by nautist** [Chlumsky/msdfgen#79]
My problem is that it seems very slow to me. I used 64*64 bitmaps for each character (at this size, rendering msdf seems just perfect), and conversion of 512 glyphs of arial bold (starting with space) takes more than 5 minutes. Is this something I have to deal with, or did I do something wrong?

**Comment by Chlumsky** [comment]
It is true that the algorithm is not optimized for performance (it inspects each edge segment at each pixel), but for a simple font like Arial (with low number of edge segments), it is still reasonably fast. For the scenario you have described, I could imagine a runtime of 5 - 15 seconds, but 5 minutes seems excessive. Are you perhaps running a debug build?

**Comment by nautist** [comment]
Wow.
First of all, thank you for the fast response. I never thought it could be such a difference in performance between a debug and a release build. But there is: >5 minutes vs maybe 10 seconds. 10 seconds is quite OK for the conversion of a font and more than worth it for the undeniably superior quality compared to a single channel sdf even at higher resoulution.

**Comment by sry948749099** [comment]
> My problem is that it seems very slow to me. I used 64*64 bitmaps for each character (at this size, rendering msdf seems just perfect), and conversion of 512 glyphs of arial bold (starting with space) takes more than 5 minutes. Is this something I have to deal with, or did I do something wrong?

i also want to generate sdf image for all the glyph of a ttf_font file, so could you tell me how you did it?

**Comment by nautist** [comment]
I used FreeType originally, but since I work on Windows, in the end I preferred GDI and convert a font one glyph at a time. I use at least a 64*64 size for each glyph to get a good quality sdf.
