### ISSUE TITLE
Artifacts occur in kanji with acute angle when msdf output

### ISSUE THREAD

**Issue by kakkou** [Chlumsky/msdfgen#80]
The characters listed in the example are kanji called `Skip StdB` ` 鍛 `manufactured by Fontworks.
When msdf is output, an unexpected line is generated from the part where the radical parts stick and the acute angle is formed.
If you draw a large font, it will be a problem because this part will look like a line.

- 8x to 64x64
![output_zoom](https://user-images.githubusercontent.com/696724/62446114-dce09e00-b79c-11e9-8002-7a7f042eee7f.png)

- Example glyph
![picture243-1](https://user-images.githubusercontent.com/696724/62446321-63957b00-b79d-11e9-8575-bac2a66f9e9c.png)

- Problem location
![picture243-2](https://user-images.githubusercontent.com/696724/62446324-65f7d500-b79d-11e9-98c6-bca8c6fe813b.png)

It is attached because it reproduces even the glyph converted to SVG.
Output with the following options
`msdfgen.exe msdf -svg test.svg -autoframe -size 64 64`
[test.zip](https://github.com/Chlumsky/msdfgen/files/3466370/test.zip)

**Comment by Chlumsky** [comment]
I believe this is the same issue as #56. The control point of the top left curve in the close-up is touching the vertical line, which means that the effective angle at the corner is 0°. The resulting artifact is technically the correct extension of the corner downward to infinity. This is an edge case that I haven't solved yet.

The obvious fix would be to move the control point slightly to the left, but of course, this cannot be expected to be done for each individual character manually. The edge case could be detected by the program, but I'm not sure how it could be automatically corrected without messing up the shape in any of the possible cases.

**Comment by fire** [comment]
What fails if we disable the corner downward to infinity case?

**Comment by Chlumsky** [comment]
What exactly do you mean by "disable"?

**Comment by fire** [comment]
Are you able to implement this?

https://link.springer.com/article/10.1007/s00371-019-01683-w

![image](https://user-images.githubusercontent.com/32321/94074493-3bf0e000-fdae-11ea-8c75-d82e901560cc.png)

The original source is in 3d, but it should work in 2d too.

**Comment by fire** [comment]
Part one seems to be a voxel type structure.

Part two describes instead of a ray, you could use a curve.

> This procedure so far is susceptible to slight changes in geometry. In the most extreme case, very small holes in an otherwise closed model, all aligned with the rays, will result in a misclassification. To counter this problem, we use the fact that the winding number does not depend on a ray, but can be an arbitrary curve going through the point to infinity. This can be thought of as follows: If we smoothly deform the surface without crossing the query point, the winding number must stay the same. For the number to change, the query point would need to cross a surface boundary. For a ray that counts intersections, this procedure would only possibly change the number of intersections encountered, not the sum of signed intersections itself as that would mean the winding number changed. We can construct the same intersection configuration by not deforming the surface but the ray instead. Figure 6 illustrates this.

![image](https://user-images.githubusercontent.com/32321/94075575-52983680-fdb0-11ea-9684-a18ade4ec7a4.png)

**Comment by Chlumsky** [comment]
No, what you've linked is about scanlines / raycasting, this is not related at all. The artifact is a vertical line in this case because the vertex bisector is vertical, but it can just as well be diagonal in a different scenario. I think I have an idea how to solve it though.

**Comment by fire** [comment]
I tested the latest and the change on https://github.com/Chlumsky/msdfgen/commit/82364f92ecfc8d7282dc746363d976144953d7c0 seemed to solve the problem. Will do some more testing.

**Comment by Chlumsky** [comment]
That wasn't the fix though.

**Comment by Chlumsky** [comment]
This issue should be resolved by 80039d7ed6c275f381eeaface5378c02870fe462 and other recent fixes present in the v1.8 release.
