### ISSUE TITLE
Combining MSDF with SDF encoded in the alpha channel

### ISSUE THREAD

**Issue by maltaisn** [Chlumsky/msdfgen#81]
MSDF is great for keeping all the sharp corners, but sometimes having rounded corners is great too. An example of this is when shadow effects are made. Here's a comparison:

**MSDF text using MSDF for shadow**
<img src="http://inter-illusion.com/assets/I2SmartEdgeManual/lib/NewItem61.png" width="100%"/>

**MSDF text using SDF in alpha channel for shadow**
<img src="http://inter-illusion.com/assets/I2SmartEdgeManual/lib/NewItem60.png" width="100%"/>

Notice how the shadow looks much more natural on the second image.

A standard distance field is encoded in the alpha channel while the other channels encode the MSDF, so both are accessible in the fragment shader. I took these images from [SmartEdge](http://inter-illusion.com/assets/I2SmartEdgeManual/SmartEdge.html?WhatSDFFormattouse.html). They call it "MSDFA". However this is a commercial library so I can't use it for generating fonts.

Would it be hard to implement this format into your generator? Since you already have MSDF and SDF I'm guessing combining them would be pretty straightforward. I'm not very familiar with C++ but I can try to make a pull request if you want.

**Comment by Chlumsky** [comment]
Yes, it would be quite easy to implement. You can also acomplish this by combining the SDF and MSDF outputs using a separate script.

**Comment by Chlumsky** [comment]
This has been added in e93c8d988cb5f71ed7318fa9424b4dda4fb6e58b, now released as version 1.7. The mode is called `mtsdf` (multi-channel & true signed distance field).
