### ISSUE TITLE
msdf font bitmap looks inverted

### ISSUE THREAD

**Issue by nautist** [Chlumsky/msdfgen#83]
Hi,
I am working on converting any installed font to a single bitmap. Most fonts I tried are fine, with but some, it looks inverted, even with single channel sdf, characters are black on white. Msdf also looks similar, rounded characters with no edges are black on a white background.
It is possible that I do something wrong, but I just don't know what can it be. What can be the cause of something like this?
Thanks.

**Comment by nautist** [comment]
Please disregard, I got it.

**Comment by spencer-evans-pnt** [comment]
What did you do to solve this? I'm having the same issue.
