### ISSUE TITLE
Can u add support to fonts where letters has WinDescent?

### ISSUE THREAD

**Issue by alexeik** [Chlumsky/msdfgen#84]
![image](https://user-images.githubusercontent.com/318732/66180744-dd9b9080-e676-11e9-83ff-6bc13797f183.png)
Letter that has WinDescent cuts by msdfgen.

REsult
![image](https://user-images.githubusercontent.com/318732/66180918-74684d00-e677-11e9-8fa0-6a0ca6eb52ae.png)

**Comment by Chlumsky** [comment]
I don't understand what this has to do with my project. The bounds of the output are fully configurable.

**Comment by alexeik** [comment]
how to configure?

**Comment by Chlumsky** [comment]
With `-translate` and `-scale`.
