### ISSUE TITLE
An question about using msdfgen 

### ISSUE THREAD

**Issue by iomeone** [Chlumsky/msdfgen#89]
Hi, sorry to borther you again!

For example , original svg is 
`<svg width="85" height="74" >   <path  d="M23.26998815917969,9.999998535156237c3.168,0 6.217,1.614 6.217,5.141c0,4.244 -3.347,7.173 -6.157,8.847c-2.152,1.315 -4.543,2.152 -7.053,2.152c-3.169,0 -6.277,-1.614 -6.277,-5.141c0,-4.244 3.407,-7.173 6.217,-8.847c2.152,-1.315 4.543,-2.152 7.053,-2.152Z"  > </path> </svg>`
the command I used is :
msdfgen.exe msdf -svg test.svg -o test.png -autoframe -size 85 74 -pxrange 37 -testrender testrender.png 85 74

the generated png is :
![36](https://user-images.githubusercontent.com/46809140/70370207-2550c980-18ff-11ea-89c0-3d5166ed7b40.png)

the render png is :
![36Render](https://user-images.githubusercontent.com/46809140/70370211-3699d600-18ff-11ea-9f15-be6be340056e.png)

but the result I want to generate is :
![109Render](https://user-images.githubusercontent.com/46809140/70370252-ed965180-18ff-11ea-8836-f76e2edba8db.png)

I want the circle full fill the whole png, How can I tweak the args to make this happen? 

The reason I want to do this is that: 
I just need to know the distance to the edge,  so I can do some fancy effects with shader! 
but I want to leave the shape size unchanged.

Thank you very much!

**Comment by Chlumsky** [comment]
Well, according to `-printmetrics`, the bounding rectangle of the shape's coordinates is about 19.5 x 16.14 units, so if you want the SDF to be 85 x 74, then 85/19.5 = 4.359, so you need to add something like `-scale 4.3`.

As for your stated reason why you need this, I don't really understand, since if you're using a shader, you can literally make it any size you want from the SDF you already have.

**Comment by iomeone** [comment]
Yes, you are right that I can make it any size I want using a shader. 
I just have a 2d scene to layout some text,  originally all the msdf texture is generated with the  -pxrange args of 2.
But now I want to change the pxrange args to a different value(much more big).
So the layout is completely changed.  each character's bounding rectangle  is shrank.
For example,  Originally the text coordinate is  2, 2  and width is 20 , 20
Using newly generated Texture, the text's x y coordinate will be changed to 11 , 11 , 
And width height'll be changed to 10 ,10 (for example)
I wonder if there is some quick way to fix this, or I need to Recalculate the whole layout.

**Comment by Chlumsky** [comment]
So, first of all, if you're generating any kind of "layout", stop using autoframe, I don't know why I have to keep saying that to everyone. It wouldn't have happened then.

What you can do now is maybe increase the output image size by the same amount as you increased `pxrange` (or twice that?), or you can do `-autoframe -printmetrics` with the original settings and then pass the scale and translation it outputs with the new `pxrange`. Something like that.

In any case, I hope you're not making a character atlas by hand.

**Comment by iomeone** [comment]
Ok, I finally understand what's going on! 
Thank you for your time , I 'll try both method you suggested!

**Comment by iomeone** [comment]
I turns out your suggestion of ( increase the output image size by the same amount as you increased) works pretty well ! thank you!
