### ISSUE TITLE
Unclear usage of Shape's bounds function

### ISSUE THREAD

**Issue by sergeyreznik** [Chlumsky/msdfgen#91]
Calling Shape's `bounds` function implicitly assumes that `l, b, t and r`  values should be properly initialized. This is not obvious, and could lead to the incorrect bounding boxes. 

For example, I was default initializing this values with zero, while actual frame was above zero, and this resulted with bbox like {0, 0, r, t} rather than {l, b, r, t} (where l, t, r, b are some concrete values).

I've created PR to fix this:
https://github.com/Chlumsky/msdfgen/pull/90

**Comment by Chlumsky** [comment]
The `Shape` class bounds API has been revised to improve clarity.
