### ISSUE TITLE
How to maintain bitmap data?

### ISSUE THREAD

**Issue by BrodaJarek** [Chlumsky/msdfgen#92]
I do not want to save glyph to a png file. I just need raw data that I can move around my application and maybe somewhere put this data to a opengl texture (or D3D, whatever).

Changing a bit your example I'd look like this:

Lets say it is a font class
```cpp
//Public data
BitmapRef<FloatRGB> ref;
Shape shape;

void LoadAGlyph()
{
FreetypeHandle *ft = initializeFreetype();
    if (ft) {
        FontHandle *font = loadFont(ft, "C:\\Windows\\Fonts\\arialbd.ttf");
        if (font) {
            if (loadGlyph(shape, font, 'A')) {
                shape.normalize();
                //                      max. angle
                edgeColoringSimple(shape, 3.0);
                //           image width, height
                Bitmap<FloatRGB> msdf(32, 32);
                //                     range, scale, translation
                generateMSDF(msdf, shape, 4.0, 1.0, Vector2(4.0, 4.0));
                ref = std::move(msdf);
            }
        }
    }
}
```
and lets say it is a renderer class and we want to update data to the texture
```cpp
    texture->UpdateData(ref.pixels);
```
the example produces these images:
![image](https://user-images.githubusercontent.com/47335145/70847324-acec8a00-1e63-11ea-92d6-5ebc73123e67.png)

![image](https://user-images.githubusercontent.com/47335145/70847350-1371a800-1e64-11ea-928b-5529bace1b82.png)

they're pretty random.

Even worse case is when I try to update texture inside a `LoadAGlyph()` method, because either 1/2 dots or 0 occurs:
```cpp
void LoadAGlyph()
{
FreetypeHandle *ft = initializeFreetype();
    if (ft) {
        FontHandle *font = loadFont(ft, "C:\\Windows\\Fonts\\arialbd.ttf");
        if (font) {
            if (loadGlyph(shape, font, 'A')) {
                shape.normalize();
                //                      max. angle
                edgeColoringSimple(shape, 3.0);
                //           image width, height
                Bitmap<FloatRGB> msdf(32, 32);
                //                     range, scale, translation
                generateMSDF(msdf, shape, 4.0, 1.0, Vector2(4.0, 4.0));
                ref = std::move(msdf);
            }
        }
    }
    texture->UpdateData(ref.pixels);
}
```

There is no problem if I update a texture right after `ref = std::move(msdf);`:

```cpp
void LoadAGlyph()
{
FreetypeHandle *ft = initializeFreetype();
    if (ft) {
        FontHandle *font = loadFont(ft, "C:\\Windows\\Fonts\\arialbd.ttf");
        if (font) {
            if (loadGlyph(shape, font, 'A')) {
                shape.normalize();
                //                      max. angle
                edgeColoringSimple(shape, 3.0);
                //           image width, height
                Bitmap<FloatRGB> msdf(32, 32);
                //                     range, scale, translation
                generateMSDF(msdf, shape, 4.0, 1.0, Vector2(4.0, 4.0));
                ref = std::move(msdf);
                texture->UpdateData(ref.pixels);
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/47335145/70847448-bd513480-1e64-11ea-9663-468180b31c91.png)

uvs are flipped, but that is not a big deal.

I am 100% sure is is not a problem with my texture class.

I do not even know how to actually ask this question properly.

How can I be able to move glyph bitmap data around my application?

**Comment by Chlumsky** [comment]
The `Bitmap` template class physically stores bitmap data, while the `BitmapRef` template class merely references bitmap data stored elsewhere and allows to use a different bitmap representation (other than `msdfgen::Bitmap`). I know this isn't really documented in detail but I thought it should be obvious even from the name.

What you are trying to do is `std::move` an actual `Bitmap` into a `BitmapRef`. This will compile because `std::move` is just an l-value cast and `Bitmap` is considered a `BitmapRef`, but the operation doesn't make sense. The pixels are still stored in the `Bitmap` class which is promptly deleted when the program leaves its scope and you are left with an invalid bitmap reference.

I think if you just use `Bitmap` instead of `BitmapRef` it should work.

**Comment by BrodaJarek** [comment]
That is correct. It works. Thank you.
