### ISSUE TITLE
Glitches on NotoSans-Regular

### ISSUE THREAD

**Issue by trethaller** [Chlumsky/msdfgen#93]
Glitches appear on at least the following characters on NotoSans-Regular:
`: ~ + - "   ] ( ) \ | { } [ ]`

Example use:
```
msdfgen.exe sdf -size 4 4 -font NotoSans-Regular.ttf ':' -size 25 25 -o a.png
msdfgen.exe sdf -size 4 4 -font NotoSans-Regular.ttf '-' -size 25 25 -o b.png
msdfgen.exe sdf -size 4 4 -font NotoSans-Regular.ttf '~' -size 25 25 -o c.png
```

![image](https://user-images.githubusercontent.com/1499344/72150971-37fb6a00-33a7-11ea-8475-2b71e1d8d10b.png) ![image](https://user-images.githubusercontent.com/1499344/72150982-434e9580-33a7-11ea-969b-a9158b6591a4.png) ![image](https://user-images.githubusercontent.com/1499344/72150996-4e092a80-33a7-11ea-9d4d-2d50e7e09b28.png)

Glitches disappear when using Italic or Medium font weights. Freetype rendering of this font produces clean results however.

**Comment by Chlumsky** [comment]
The geometry of these particular glyphs contains a strange artifact. When I print out the vertices of the minus character, I get:

```
{
	1.5625, 8.1875;
	1.5625, 10.8125;
	9.3125, 10.8125;
	9.3125, 8.1875;
	#
}
{
	7.078125, 19.90625;
	7.078125, 19.90625;
	7.078125, 19.90625;
	#
}
```

As you can see, the second part is a degenerate triangle where all three points are identical. This seems to completely confuse my algorithm, which strictly requires the input to "make sense". I guess scanline based rasterizers are not affected, so not even the font designer noticed.

The reason I didn't implement any sort of geometry correction is that I didn't think I would be able to identify all possible artifacts anyway and that I couldn't avoid false positives, so my philosophy was that whoever uses my library has to make sure the input is valid. Now though I think I might need to do something about at least the most obvious cases such as this one.

**Comment by Chlumsky** [comment]
Alright, I have fixed this particular edge case in the font import routine.

**Comment by trethaller** [comment]
Thanks for the quick fix!
