### ISSUE TITLE
SDF and PSDF produce the same texture

### ISSUE THREAD

**Issue by oomek** [Chlumsky/msdfgen#94]
Maybe I do not understand something, but it looks like the psdf switch does not work. I compared high resolution sdf and psdf outputs and they look exactly the same with rounded corners. Shouldn't psdf output have sharp corners?
![image](https://user-images.githubusercontent.com/2974860/72384549-990f9e80-3715-11ea-9ddf-bcf777bb0673.png)

**Comment by Chlumsky** [comment]
You need to provide the data you used to generate this.

**Comment by oomek** [comment]
It's barlow condensed font

**Comment by Chlumsky** [comment]
The font has rounded corners.

**Comment by oomek** [comment]
I know, but the roundness in the font is miniscule compared to the roudness applied to the texture

**Comment by Chlumsky** [comment]
I have no idea what kind of output you're expecting. It's not going to magically redesign the font or decide that some curves are too small and just cut them out.
